### ISSUE TITLE
Bulbs are not correctly classified

### ISSUE THREAD

**Issue by reloadedhead** [AMoo-Miki/homebridge-tuya-lan#10]
Some time ago I tried this plugin with my Teckin bulbs with no problems at all on my Mac. I purchased a Pi and installed homebridge in it. However, they appear as a SimpleLight in the home app (even when I set them as RGB lights on the config.json file), and the commands are unresponsive, on/off don't work. ID and Key are ok, because they seem to work with other tuya plugins. Any ideas?

**Comment by AMoo-Miki** [comment]
Any change to the config file would need a removal of `cachedAccessories` from your `.homebridge` folder. This is often found at `~/.homebridge/accessories/cachedAccessories`.

Let me know how things go and we can debug it together.

Good luck.

**Comment by xatrix78** [comment]
I have the same Problem with Bulbs and outlets.

`  {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Küchenlampe",
                    "type": "RGBTWLight",
                    "manufacturer": "Lyasi",
                    "model": "E27 9 Watt",
                    "id": "xx",
                    "key": "xx"
                },
                {
                    "name": "Waschmaschiene",
                    "type": "Outlet",
                    "manufacturer": "Gosund",
                    "model": "SP1--2",
                    "id": "xx",
                    "key": "xx"
                },
                {
                    "name": "Trockner",
                    "type": "Outlet",
                    "manufacturer": "Gosund",
                    "model": "SP1--2",
                    "id": "xx",
                    "key": "xx"
                }
            ]
        },`

**Comment by xatrix78** [comment]
No function and reaction when I switch an outlet or bulb on. no error in the log about it.

**Comment by AMoo-Miki** [comment]
Make sure no Tuya Smart Life or any other app that controls your bulbs and outlets is open. Restart `Homebridge`. When `Homebridge` starts, look for the following messages:
```
[TuyaLan] Ready to handle Küchenlampe ...
[TuyaLan] Ready to handle Waschmaschiene ...
[TuyaLan] Ready to handle Trockner ...

[TuyaLan] Failed to discover Küchenlampe
[TuyaLan] Failed to discover Waschmaschiene
[TuyaLan] Failed to discover Trockner
```
Which ones do you see? Please paste the complete line here.

Next, in the Home app, try changing turning one on or off; is the button clickable? If yes, look at the logs for
```
[TuyaAccessory] Sending ... { ... }
```
Does it appear? If yes, do you see `Sending HTTP event '100.xx' with data` immediately after it?

Look for errors when `Homebridge` starts; there might be more messages there.

**Comment by reloadedhead** [comment]
[3/22/2019, 3:01:29 PM] [TuyaLan] Starting discovery...
[3/22/2019, 3:01:29 PM] Homebridge is running on port 51830.
[TuyaAccessory] Discovery started.
[3/22/2019, 3:01:29 PM] [TuyaLan] Discovered Luz lateral 2 (20437567840d8e984a6f)
[3/22/2019, 3:01:31 PM] [TuyaLan] Connected to Luz lateral 2
[3/22/2019, 3:01:31 PM] [TuyaLan] Discovered Luz lateral 1 (60427044cc50e326b6ab)
[TuyaAccessory] Discovery ended.
[3/22/2019, 3:01:31 PM] [TuyaLan] Connected to Luz lateral 1
[3/22/2019, 3:02:12 PM] [Config] Using Form Authentication
[3/22/2019, 3:02:12 PM] [Config] Console v3.9.7 is listening on port 8080.
[3/22/2019, 3:02:40 PM] [TuyaLan] Luz lateral 1 - identify
[3/22/2019, 3:02:49 PM] [TuyaLan] Luz lateral 2 - identify

There are not errors when Homebridge starts.

**Comment by AMoo-Miki** [comment]
When you try switching them on or off, don't you see the `Sending` message?

Just to make sure you are using the latest code, please run `npm i -g AMoo-Miki/homebridge-tuya-lan` and restart Homebridge, then recheck.

**Comment by reloadedhead** [comment]
I do not see `Sending` message. However, it does connect to both bulbs:
`[TuyaAccessory] Discovery started.
[4/7/2019, 10:59:30 PM] [TuyaLan] Discovered Luz lateral 1 (60427044cc50e326b6ab)
[4/7/2019, 10:59:30 PM] [TuyaLan] Connected to Luz lateral 1
[4/7/2019, 10:59:31 PM] [TuyaLan] Discovered Luz lateral 2 (20437567840d8e984a6f)
[TuyaAccessory] Discovery ended.
[4/7/2019, 10:59:31 PM] [TuyaLan] Connected to Luz lateral 2`

It also logs this:
`[4/7/2019, 11:01:27 PM] [TuyaLan] Luz lateral 1 - identify
[4/7/2019, 11:01:38 PM] [TuyaLan] Luz lateral 1 - identify
[4/7/2019, 11:01:40 PM] [TuyaLan] Luz lateral 2 - identify`

Even though I set the type to RGB bulbs, they show up as simple bulbs, and the buttons on home app do not work. I guess the plugin can establish communication with the bulbs. Any ideas?

**Comment by AMoo-Miki** [comment]
@reloadedhead, please post your config block for this plugin here; scratch out the `key` values just to be safe. Also could you confirm that you did update to the latest code?

**Comment by reloadedhead** [comment]
I have reinstalled the plugin yesterday so I’m pretty sure I’m on the latest version. Here’s my config. Apologies for the format, I’m on mobile. 
{
"platform": "TuyaLan",
"devices": [
{
"name": "Luz lateral 1",
"type": "RGBTWLight",
"manufacturer": "Teckin",
"model": "Smart Wifi Bulb Socket E26",
"id": "id",
"key": "key"
},
{
"type": "RGBTWLight",
"manufacturer": "Teckin",
"model": "Smart Wifi Bulb Socket E26",
"name": "Luz lateral 2",
"id": "id",
"key": "key"
}
]
},

**Comment by AMoo-Miki** [comment]
@reloadedhead, can you confirm that you installed using `npm i -g AMoo-Miki/homebridge-tuya-lan`? Also can you please check your logs for the `Sending` entries when you try to make changes using the Home app?

**Comment by AMoo-Miki** [comment]
The Teckins use a newer API. Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.
