### ISSUE TITLE
Not Detecting Downlight

### ISSUE THREAD

**Issue by IchabodFletchman** [AMoo-Miki/homebridge-tuya-lan#102]
I have successfully set up an RGB downlight inside "TuyaSmart" app.
Homebridge log doesn't seem to be showing any activity of finding the light. I have enabled debug logging and the only output from this plugin is `[TuyaLan] Starting discovery...
[TuyaAccessory] Discovery started.` which is on initial Homebridge startup, no updates since.

Downlight: [https://www.kmart.com.au/product/mirabella-genio-9w-led-wi-fi-dimmable-downlight/2754330](url)

I also grabbed the schema if that helps

```
Found 1 device:
[
	{
		name: 'Downlight',
		id: 'xxxxxxxxxxxxxxxxxxxx',
		key: 'xxxxxxxxxxxxxxxx',
		def:	{
			schema: '[{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-dp_power2","id":20,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","music"],"type":"enum"},"iconname":"icon-dp_list","id":21,"type":"obj","desc":""},{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6\\u503c","property":{"unit":"","min":10,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_sun","id":22,"type":"obj","desc":""},{"mode":"rw","code":"temp_value","name":"\\u51b7\\u6696\\u503c","property":{"unit":"","min":0,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_half","id":23,"type":"obj","desc":""},{"mode":"rw","code":"colour_data","name":"\\u5f69\\u5149","property":{"type":"string","maxlen":255},"iconname":"icon-dp_light","id":24,"type":"obj","desc":""},{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"iconname":"icon-dp_box2","id":25,"type":"obj","desc":""},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-timer1","id":26,"type":"obj","desc":""},{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"iconname":"icon-setting","id":28,"type":"obj","desc":""}]',
			extras: '[{"id":22,"inputStyle":"","inputType":"percent"},{"id":23,"inputStyle":"","inputType":"percent"},{"id":26,"inputStyle":"","inputType":""}]',
		}
	}
]  
```

**Comment by IchabodFletchman** [comment]
I managed to get the signature too:
`[TuyaLan] Ready to handle Downlight (SimpleLight:3.3) with signature {"20":false,"21":"white","22":10,"23":446,"24":"012303e8000a","25":"000e0d00002e03e802cc00000000","26":0}`

**Comment by crmunro** [comment]
I'm working on a very similar light at the moment, the non-RGB version of that same Mirabella Genio downlight. I have it communicating but not updating on the latest RC,  v1.5.0-rc.12 as [per this issue](https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/33#issuecomment-528818678). 

The downlight is from here: https://www.kmart.com.au/product/mirabella-genio-wi-fi-dimmable-9w-led-downlight/2754331

Signature: `Ready to handle Downlight (SimpleLight:3.3) with signature {"20":true,"21":"white","22":1000,"23":193,"25":"000e0d00002e03e8000000c80000","26":0}`

Schema: 
```Found 1 device:
[
  {
    name: 'Genio CCT Downlight 2',
    id: '80304313dc4f229a2367',
    key: '1a1e5510ca545f4c',
    def: {
      schema: '[
      		{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"iconname":"icon-dp_power2","id":20,"type":"obj","desc":""},
      		{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","music"],"type":"enum"},"iconname":"icon-dp_list","id":21,"type":"obj","desc":""},
      		{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6\\u503c","property":{"unit":"","min":10,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_sun","id":22,"type":"obj","desc":""},
      		{"mode":"rw","code":"temp_value","name":"\\u51b7\\u6696\\u503c","property":{"unit":"","min":0,"max":1000,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_half","id":23,"type":"obj","desc":""},
      		{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"iconname":"icon-dp_box2","id":25,"type":"obj","desc":""},
      		{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-timer1","id":26,"type":"obj","desc":""},
      		{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"iconname":"icon-setting","id":28,"type":"obj","desc":""}
      	]',
    },
  },
]```

Off to try to figure out how to update this myself!

**Comment by crmunro** [comment]
Now have this working, without any changed needed to homebridge-tuya-lan. All I needed to do was to modify my homebridge config.json with the following information, as [per this issue](https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/81). Discoverability was an issue, so I have manually pointed to the IP address.

```
"platform": "TuyaLan",
            "devices": [
                {
                    "name": "Kitchen Downlight",
                    "type": "TWLight",
                    "manufacturer": "Mirabella",
                    "model": "Genio Downlight CW",
                    "id": "xxxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxx",
                    "ip": "192.168.1.115",
                    "dpPower": 20,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "minWhiteColor": 0,
                    "maxWhiteColor": 1000,
                    "scaleBrightness": 1000,
                    "scaleWhiteColor": 1000
                }
            ]

```

@IchabodFletchman – this additional config may work for your device as well?

**Comment by IchabodFletchman** [comment]
@crmunro 
That is great that you have gotten it to work and appreciate the info.
I haven't been so fortunate. I tried to configure mine with the same details (TWLight, Power, Brightness, etc) and my static IP address for the light.
I wasn't successful with that, so I tried adding it as a 'RGBTWLight' with the details from the user in your above link:
```
{
  "name": "RGB Downlight",
  "type": "RGBTWLight",
  "manufacturer": "Mirabella",
  "model": "Genio 9W LED Wi-Fi Dimmable Downlight",
  "id": "xxxxxxxxxxxxxxx",
  "key": "xxxxxxxxxxxxx",
  "ip": "192.168.1.123",
  "dpPower": "20",
  "dpMode": "21",
  "dpBrightness": "22",
  "dpColorTemperature": "23",
  "dpColor": "24",
  "maxWhiteColor": "221",
  "colorFunction": "HSB",
  "minBrightness": 10,
  "scaleBrightness": 1000,
  "scaleWhiteColor": 1000
},
```

The light shows inside HomeKit, but the power toggle doesn't work at all, and there aren't any brightness and RGB options.

The only log I'm getting from HomeBridge (with both light types) is:
```
[10/19/2019, 11:47:02 PM] [TuyaLan] Discovered RGB Downlight (45527580c44f339880da) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for RGB Downlight to 9s
[10/19/2019, 11:47:02 PM] [TuyaLan] Connected to RGB Downlight
[TuyaAccessory] Sending first query to RGB Downlight (3.3)
[TuyaAccessory] Odd message from RGB Downlight with command 10: ˢ�[���J�P�}�i�C���<WG��m]��ڕ�3
[TuyaAccessory] Raw message from RGB Downlight (3.3) with command 10: 000055aa000000000000000a0000002c00000001cba2aa5bf5a5894adc50a57dfb69fc43bbfcec3c5747c9cd6d5dafa4da959f338ebc27c20000aa55
```

And I'm not getting any logs when tapping the on/off state in Homekit, not sure if it's supposed to since I don't have any other Tuya devices to use.

Does the brightness/dimming work with your downlight?
If your light works 100%, I might pickup a couple of whites only, I only bought the RGB ones because they were only $4 more, I believe I would rarely use the RGB function in a downlight anyway.

**Comment by TheHomekitWayFinder** [comment]
@IchabodFletchman it appears as if your key might not be correct which can be due to a number of reasons, so what I would suggest is that you acquire the key again and make sure that the key you are using is correct. [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IchabodFletchman** [comment]
@TheHomekitWayFinder - Thanks heaps for that! I'm not sure why my key changed, I must have done something to reset the key at some stage during my troubleshooting, didn't think to check that myself.

I'm happy to report that this Downlight is fully operational. RGB/White/Dimming.
There is a bunch of other Mirabella Tuya devices available. I might pick up some other stuff and see if I can get them running in HomeKit!

**Comment by TheHomekitWayFinder** [comment]
>@TheHomekitWayFinder - Thanks heaps for that! I'm not sure why my key changed, I must have done something to reset the key at some stage during my troubleshooting, didn't think to check that myself. ...

@IchabodFletchman no problems. Yeah I know about the mirabella devices however I’m not sure whether the sensors will work as from what I have determined the sensors only communicate when the door or window is open or closed and therefore homebridge doesn’t discover the device as I picked up one the other week and I haven’t managed to get it working. I also have a Kogan AC Unit and that works well. All of the Kogan stuff along with the mirrabella stuff and Grid connect stuff (available are Bunnings) all use Tuya and work really well in HomeKit. If you want sensors I recommend buying HomeKit certified sensors at the moment such as Eve sensors or if you don’t wanna spend $70+ on a sensor then you can always pick up a Aqara Hub and their sensors which apparently work well with HomeKit, I have just ordered one to try for motion, temperature, door window sensors but it also supports plugs and many other devices but because it comes from China you have to pay exchange rates so when you get the hub for about $39 US on special then it works out about $75 AU. But then the sensors are like $15 each on special and they’re constantly on special

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IchabodFletchman** [comment]
Funny enough, I ordered an Aqara hub with a few button switches and temperature sensor and vibration sensor last week. I bought them through eBay from Victoria.
They should arrive during the week... hopefully
