### ISSUE TITLE
Having issues setting up with Homebridge

### ISSUE THREAD

**Issue by Gabriel-H4** [AMoo-Miki/homebridge-tuya-lan#103]
[my-config.zip](https://github.com/AMoo-Miki/homebridge-tuya-lan/files/3736273/my-config.zip)
![Screen Shot 2019-10-16 at 3 32 11 PM](https://user-images.githubusercontent.com/56655458/66956572-36c9d380-f02a-11e9-9f32-17c5816659b5.png)

Here's my config.json and screenshot of terminal. How should I fix this?

**Comment by iRayanKhan** [comment]
Why do you have Tuya Smart as an accessory? Why not use this plugin to expose it?
Also next time don't upload your ```config.json``` as a .zip, either paste it here or upload it to [Paste Bin](pastebin.com)

**Comment by codyc1515** [comment]
You need to follow instructions given on the main page. Accordingly, your config.json file should look something like this:

```
{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "description":"This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
   "ports":{
      "start":52100,
      "end":52150,
      "comment":"This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
   },
   "accessories":[
      {

      }
   ],
   "platforms":[
      {
         "platform":"TuyaLan",
         "devices":[
            {
               "name":"My Lights",
               "type":"SimpleLight",
               "manufacturer":"The Electrical Products Company",
               "model":"Single Gang Light Switch",
               "id":"XXX",
               "key":"XXX"
            }
         ]
      }
   ]
}
```
