### ISSUE TITLE
Switching from colour to white

### ISSUE THREAD

**Issue by quacktacular** [AMoo-Miki/homebridge-tuya-lan#11]
Well done this is a great plugin!

Do you know wether there is a simple way to have Siri / HomeKit change the lights from color mode to white / warm white etc? 

I was able to create a scene to do it, but as soon as I add any of my Hue lights to the scene something weird happens. The Tuya lights will enter white mode, with the correct temperature, but then they'll turn that weird violet colour that you get when you request a white in color mode.

Here's the log from when I change the scene:
```
[TuyaAccessory] Sending Kitchen 2 {"1":true}
[TuyaAccessory] Sending Kitchen 4 {"5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 4 {"1":true}
[TuyaAccessory] Sending Kitchen 1 {"2":"white","4":85}
[TuyaAccessory] Sending Kitchen 1 {"1":true}
[TuyaAccessory] Sending Pentagon {"1":true}
[TuyaAccessory] Sending Kitchen 3 {"2":"white","4":85}
[TuyaAccessory] Sending Kitchen 3 {"1":true}
[TuyaAccessory] Sending Kitchen 5 {"5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 2 {"5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 5 {"2":"white","4":85}
[TuyaAccessory] Sending Kitchen 5 {"1":true}
[TuyaAccessory] Sending Kitchen 4 {"2":"white","4":85}
[TuyaAccessory] Sending Kitchen 3 {"5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 2 {"2":"white","4":85}
[TuyaAccessory] Sending Kitchen 1 {"5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 4 {"2":"colour","5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 1 {"2":"colour","5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 5 {"2":"colour","5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 3 {"2":"colour","5":"ffcc9c001d63ff"}
[TuyaAccessory] Sending Kitchen 2 {"2":"colour","5":"ffcc9c001d63ff"}
```

I'm thinking this is HomeKit being dumb and sending a temperature and colour command. One idea would be suppress mode changes (color vs. white) within x seconds after a previous mode change (1-3 seconds should work). 

What do you think?

**Comment by quacktacular** [comment]
Another approach might just be to intercept the colour string `ffcc9c001d63ff` ("champagne" in this case) and if it's close enough to white convert to a temperature. That would avoid having to keep track of mode changes. The conversion formula might get a bit tricky though 😁

**Comment by AMoo-Miki** [comment]
Interesting. Lemme check this out on my own stuff and think a bit about your proposals.

**Comment by AMoo-Miki** [comment]
@quacktacular, I have a 500ms debounce but I put in some logic to avoid cross-mode complications due to rapid dispatch of commands. Please reopen if you still have this problem.
