### ISSUE TITLE
Deprecate homebridge-tuya

### ISSUE THREAD

**Issue by codetheweb** [AMoo-Miki/homebridge-tuya-lan#12]
Hey @AMoo-Miki,

I'm considering deprecating my [homebridge-tuya](https://www.npmjs.com/package/homebridge-tuya) plugin and pointing users to this plugin instead, as I don't have the time to maintain it and you have more devices supported at this point.  Are you ok with that?

**Comment by AMoo-Miki** [comment]
Sure. That is sad news. Any way you can reconsider deprecating?

If you do go through with it... hell yeah I would be okay! :P Your plugin would be missed.

**Comment by codetheweb** [comment]
Just officially deprecated the plugin. 😢

A bit sad, but it's probably for the best as the plugin was a drain on my time that could be better spent elsewhere in TuyAPI.
