### ISSUE TITLE
Allow dps values for tuya powerstrips

### ISSUE THREAD

**Issue by carsten-h** [AMoo-Miki/homebridge-tuya-lan#14]
Hello!

Is it possible to implement the dps option for tuya powerstrips like they were available in https://github.com/codetheweb/homebridge-tuya?

Thank you!
Carsten

**Comment by AMoo-Miki** [comment]
Hi,

I just pushed "CustomMultiOutletAccessory" that lets you do this. This is how you use it:
```json5
{
  "name": "Custom Outlet",
  "type": "CustomMultiOutlet",
  "manufacturer": "GeekBee",
  "model": "Smart WiFi Power Strip",
  "id": "xxxxxxx",
  "key": "xxxxxxxx",
  "outlets": [
    {
      "name": "Heat Gun",
      "dp": 1
    },
    {
      "name": "Solder Iron",
      "dp": 3
    }
  ]
}
```

Until I make a release, you can update the plugin with `npm i -g AMoo-Miki/homebridge-tuya-lan` and play with it. Lemme know how it works or if you have any questions.

**Comment by carsten-h** [comment]
Hello!

I tried this:


                {
                    "name": "Wohnzimmerdoppeldose",
                    "type": "CustomMultiOutlet",
                    "manufacturer": "Cotify",
                    "model": "Smart Wifi",
                    "id": "xxxxx",
                    "key": "yyyyy",
                    "outlets": [
                        {
                            "name": "Weihnachtsstern",
                            "dp": 1
                        },
                        {
                            "name": "Repeater unten",
                            "dp": 2
                        }
                    ]
                },



and what happened is this:
——
Mar 14 16:27:27 HomePi homebridge[17049]: [3/14/2019, 4:27:27 PM] [TuyaLan] Connected to Wohnzimmerdoppeldose
Mar 14 16:27:27 HomePi homebridge[17049]: [3/14/2019, 4:27:27 PM] [TuyaLan] Connected to Kamera
Mar 14 16:27:27 HomePi homebridge[17049]: [3/14/2019, 4:27:27 PM] [TuyaLan] Ready to handle Wohnzimmerdoppeldose with signature {"1":false,"2":true,"9":0,"10":0}
Mar 14 16:27:27 HomePi homebridge[17049]: /usr/local/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:34
Mar 14 16:27:27 HomePi homebridge[17049]:             const nameCharacteristic = service.getCharacteristic(Characteristic.Name) || service.addCharacteristic(Characteristic.Name);
Mar 14 16:27:27 HomePi homebridge[17049]:                                                                  ^
Mar 14 16:27:27 HomePi homebridge[17049]: ReferenceError: Characteristic is not defined
Mar 14 16:27:27 HomePi homebridge[17049]:     at CustomMultiOutletAccessory._checkServiceName (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:34:66)
Mar 14 16:27:27 HomePi homebridge[17049]:     at device.context.outlets.forEach (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/CustomMultiOutletAccessory.js:35:31)
Mar 14 16:27:27 HomePi homebridge[17049]:     at Array.forEach (<anonymous>)
Mar 14 16:27:27 HomePi homebridge[17049]:     at CustomMultiOutletAccessory._verifyCachedPlatformAccessory (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/CustomMultiOutletAccessory.js:29:37)
Mar 14 16:27:27 HomePi homebridge[17049]:     at CustomMultiOutletAccessory._registerCharacteristics (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/CustomMultiOutletAccessory.js:49:14)
Mar 14 16:27:27 HomePi homebridge[17049]:     at TuyaAccessory.BaseAccessory.device.once (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:22:18)
Mar 14 16:27:27 HomePi homebridge[17049]:     at Object.onceWrapper (events.js:285:13)
Mar 14 16:27:27 HomePi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 16:27:27 HomePi systemd[1]: homebridge.service: Unit entered failed state.
Mar 14 16:27:27 HomePi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 14 16:27:37 HomePi systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Mar 14 16:27:37 HomePi systemd[1]: Stopped Node.js HomeKit Server.
Mar 14 16:27:37 HomePi systemd[1]: Started Node.js HomeKit Server.

——

**Comment by AMoo-Miki** [comment]
I accidentally deleted a vital line after testing and before pushing it. I have fixed it now. I was way too sleepy when I wrapped this up. Let's hope that was the only thing I messed up.

**Comment by carsten-h** [comment]
Yes, now it works like a charm! Thank you very much for this!

**Comment by AMoo-Miki** [comment]
Awesome. Thanks for confirming.
