### ISSUE TITLE
Smart-Life platform support?

### ISSUE THREAD

**Issue by JBFUK** [AMoo-Miki/homebridge-tuya-lan#143]
In the config you have a platform field:

"platform": "TuyaLan"

Is it possible to add support for the smart_life platform (like the homebridge-tuya-web plugin).  I believe this is very similar to and compatible with the Tuya platform but it also supports IFTTT.

Also just wondering can this plugin control devices via wifi even without an internet connection?

**Comment by tom-23** [comment]
Both apps are mostly identical so any appliances that use Smartlife can be used with the Tuya app with no modification needed.

**Comment by bytheedgeuk** [comment]
I've added mine but had to use the Ucomen App to get the Switch ID as the latest version of the Smart Life app doesn't allow you to get the ID using the current set up instructions.

**Comment by JBFUK** [comment]
Thanks.  I ended up deciding to flash my devices with Tasmota and break free from relying on a Chinese app/cloud with dubious security and privacy.
