### ISSUE TITLE
Adding a Double Switch

### ISSUE THREAD

**Issue by bytheedgeuk** [AMoo-Miki/homebridge-tuya-lan#144]
I've managed for follow the set up instructions using the Ucomen app but I have a double switch controlling two separate sets of lights. However I'm only being show an ID and key for one of the switches.

How do I get the ID and Key for the other one?

**Comment by ScottEgan** [comment]
I believe you only need one ID and one Key if you set it up as a power strip. https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#smart-power-strips

**Comment by bytheedgeuk** [comment]
@ScottEgan Thanks, tried that and it worked! 💃
