### ISSUE TITLE
The Proxy Profile has stopped working for Smart Life and TuyaSmart Apps

### ISSUE THREAD

**Issue by chinloon** [AMoo-Miki/homebridge-tuya-lan#147]
Something has changed and the two apps's traffic are not being intercepted and deciphered anymore.  Could it be that they have implemented TLS?  Anyway, what other ways to extract the ID, keys and profile?

**Comment by TheHomekitWayFinder** [comment]
I am having the same issue the only way is to set up the device in another app and see if that works

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chinloon** [comment]
which other app can I use?

**Comment by kalety** [comment]
Ucomen Home still gets de ID and key...

**Comment by kalety** [comment]
Ucomen Home still gets de ID and key...

**Comment by kalety** [comment]
Ucomen Home still gets de ID and key...

**Comment by jesusdp** [comment]
> Ucomen Home still gets de ID and key...

@kalety did you try Ucomen Home in Android or iOS? I downloaded in iOS and it doesn't work at all.

**Comment by kalety** [comment]
In iOS... it worked for me.

**Comment by earlywaff** [comment]
Please tell me, Ucomen Home on android closed the gap? Are there any other options without an iPhone to do this.
/подскажите Ucomen Home закрыл в андроиде возможность? Сниф не работает, а в логах пустота. Есть ли возможность как-то еще сделать это?

**Comment by schmuto** [comment]
Worked for me with the Ucomen App on iOS 13.3.
Ucomen App v1.1.2 (20191209174228)

**Comment by chinloon** [comment]
Ok, will try ucomen.  A question, when does the key of the device change?  when firmware is updated or when there is loss of power and it is rebooted?

**Comment by chinloon** [comment]
Sorry, accidentally closed.  Reopened.

**Comment by schmuto** [comment]
> Ok, will try ucomen. A question, when does the key of the device change? when firmware is updated or when there is loss of power and it is rebooted?

AFAIK only when the device is unpaired via the app or reset to the factory settings. Loss of power shouldn’t change the key.

**Comment by aviogit** [comment]
I think I'm having the same problem trying to grab key for a Nooie Smart Bulb (https://www.amazon.com/Dimmable-Multicolor-Compatible-Required-Equivalent/dp/B07X1KYSBJ - Tuya FW version 1.0.5)

Running `tuya-lan-find --schema` and refreshing on the TuyaSmart app, I only get a wall of these:

> Error: Error: 140202584128384:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1500:SSL alert number 46
> 140202584128384:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1217:

The other strange thing is that the app says `Incorrect local time, please correct it. 50502`, I suspect it could be related.

**Comment by aviogit** [comment]
Uououo! I've got ID, key and schema!

I confirm that Ucomen Home 1.1.2 still works! :)

Now I don't know how to use the schema, but here it is...

> Intercepted config from Tuya
> 
> Found 1 device:
> [
>   {
>     name: 'Nooie Smart LED Bulb',
>     id: 'xxxxxxxxxxxxxxxxxxxxxx',
>     key: 'yyyyyyyyyyyyyyyy',
>     def: {
>       schema: '[{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"id":20,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene"],"type":"enum"},"id":21,"type":"obj","desc":""},{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6\\u503c","property":{"unit":"","min":10,"max":1000,"scale":0,"step":1,"type":"value"},"id":22,"type":"obj","desc":""},{"mode":"rw","code":"temp_value","name":"\\u51b7\\u6696\\u503c","property":{"unit":"","min":0,"max":1000,"scale":0,"step":1,"type":"value"},"id":23,"type":"obj","desc":""},{"mode":"rw","code":"colour_data","name":"\\u5f69\\u5149","property":{"type":"string","maxlen":255},"id":24,"type":"obj","desc":""},{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"id":25,"type":"obj","desc":"themes\\uff1a Focused, Natural, Active, Calm, Romantic, Cheerful, Playful, Floating, Mellow, \\u652f\\u6301\\u53ef\\u7f16\\u8f91\\uff0c\\u6700\\u591a\\u5341\\u4e2a\\u573a\\u666f"},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6","property":{"unit":"","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"id":26,"type":"obj","desc":""},{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"id":28,"type":"obj","desc":""},{"mode":"rw","code":"white_color","name":"\\u767d\\u5149\\u5e38\\u7528","property":{"range":["White1","White2","White3"],"type":"enum"},"id":101,"type":"obj","desc":""},{"mode":"rw","code":"full_color","name":"\\u5f69\\u5149\\u5e38\\u7528","property":{"range":["Color1","Color2","Color3"],"type":"enum"},"id":102,"type":"obj","desc":""},{"mode":"rw","code":"wakeup_mode","name":"\\u5524\\u9192\\u6a21\\u5f0f/\\u6de1\\u5165","property":{"type":"string","maxlen":255},"id":103,"type":"obj","desc":"\\"\\u652f\\u6301\\u8bbe\\u7f6e\\u5f00\\u59cb\\u65f6\\u95f4\\uff0c12/24\\u5c0f\\u65f6\\u5236\\u53ef\\u968f\\u624b\\u673a\\u8bbe\\u7f6e\\u65f6\\u95f4\\u5207\\u6362\\uff1b\\n\\u652f\\u6301\\u53ef\\u9009\\u5468\\u4e00\\u81f3\\u5468\\u65e5\\uff1b\\n\\u65f6\\u95f4\\u8303\\u56f4\\uff1a5m\\uff1b10m\\uff1b15m\\uff1b20m\\uff1b30m\\uff1b1h\\u3002\\u6bcf\\u5206\\u949f\\u4e0a\\u62a5\\u4e00\\u6b21\\"\\n"},{"mode":"rw","code":"sleep_mode","name":"\\u5165\\u7761\\u6a21\\u5f0f/\\u6de1\\u51fa","property":{"type":"string","maxlen":255},"id":104,"type":"obj","desc":"\\"\\u652f\\u6301\\u8bbe\\u7f6e\\u5f00\\u59cb\\u65f6\\u95f4\\uff0c12/24\\u5c0f\\u65f6\\u5236\\u53ef\\u968f\\u624b\\u673a\\u8bbe\\u7f6e\\u5207\\u6362\\uff1b\\n\\u652f\\u6301\\u53ef\\u9009\\u5468\\u4e00\\u81f3\\u5468\\u65e5\\uff1b\\n\\u65f6\\u95f4\\u8303\\u56f4\\uff1a5m\\uff1b10m\\uff1b15m\\uff1b20m\\uff1b30m\\uff1b1h\\u3002\\u6bcf\\u5206\\u949f\\u4e0a\\u62a5\\u4e00\\u6b21\\"\\n"}]',
>       extras: '[{"id":20,"inputStyle":"","inputType":""},{"id":21,"inputStyle":"","inputType":""},{"id":22,"inputStyle":"","inputType":""},{"id":23,"inputStyle":"","inputType":""},{"id":26,"inputStyle":"","inputType":"countdown1"},{"id":101,"inputStyle":"","inputType":""},{"id":102,"inputStyle":"","inputType":""}]',
>     },
>   },
> ]

**Comment by mrmaximas** [comment]
I confirm too than - Ucomen Home 1.1.2 works! 
Please check out two plugs:
1) Yandex Smart Outlet (metered without rgbw) 
  {
    name: 'Yandex',
   id: 'xxxxxxxxxxxxxx',
    key: 'yyyyyyyyyyyyy',
    def: {
      schema: '[{"mode":"rw","code":"switch_1","name":"\\u5f00\\u51731","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj","desc":""},{"mode":"rw","code":"countdown_1","name":"\\u5f00\\u51731\\u5012\\u8ba1\\u65f6","property":{"unit":"s","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_time2","id":9,"type":"obj","desc":""},{"mode":"rw","code":"add_ele","name":"\\u589e\\u52a0\\u7535\\u91cf","property":{"unit":"","min":0,"max":50000,"scale":3,"step":100,"type":"value"},"iconname":"icon-battery","id":17,"type":"obj","desc":""},{"mode":"ro","code":"cur_current","name":"\\u5f53\\u524d\\u7535\\u6d41","property":{"unit":"mA","min":0,"max":30000,"scale":0,"step":1,"type":"value"},"iconname":"icon-Ele","id":18,"type":"obj","desc":""},{"mode":"ro","code":"cur_power","name":"\\u5f53\\u524d\\u529f\\u7387","property":{"unit":"W","min":0,"max":50000,"scale":1,"step":1,"type":"value"},"iconname":"icon-dp_tool","id":19,"type":"obj","desc":""},{"mode":"ro","code":"cur_voltage","name":"\\u5f53\\u524d\\u7535\\u538b","property":{"unit":"V","min":0,"max":5000,"scale":1,"step":1,"type":"value"},"iconname":"icon-a_function_turbo","id":20,"type":"obj","desc":""},{"mode":"ro","code":"test_bit","name":"\\u4ea7\\u6d4b\\u7ed3\\u679c\\u4f4d","property":{"unit":"","min":0,"max":5,"scale":0,"step":1,"type":"value"},"iconname":"icon-dp_direction","id":21,"type":"obj","desc":""},{"mode":"ro","code":"voltage_coe","name":"\\u7535\\u538b\\u6821\\u51c6\\u7cfb\\u6570","property":{"unit":"","min":0,"max":1000000,"scale":0,"step":1,"type":"value"},"iconname":"icon-gaodiyin","id":22,"type":"obj","desc":""},{"mode":"ro","code":"electric_coe","name":"\\u7535\\u6d41\\u6821\\u51c6\\u7cfb\\u6570","property":{"unit":"","min":0,"max":1000000,"scale":0,"step":1,"type":"value"},"iconname":"icon-gaodiyin","id":23,"type":"obj","desc":""},{"mode":"ro","code":"power_coe","name":"\\u529f\\u7387\\u6821\\u51c6\\u7cfb\\u6570","property":{"unit":"","min":0,"max":1000000,"scale":0,"step":1,"type":"value"},"iconname":"icon-gaodiyin","id":24,"type":"obj","desc":""},{"mode":"ro","code":"electricity_coe","name":"\\u7535\\u91cf\\u6821\\u51c6\\u7cfb\\u6570","property":{"unit":"","min":0,"max":1000000,"scale":0,"step":1,"type":"value"},"iconname":"icon-gaodiyin","id":25,"type":"obj","desc":""},{"mode":"ro","code":"fault","scope":"fault","name":"\\u6545\\u969c\\u544a\\u8b66","property":{"label":["ov_cr"],"type":"bitmap","maxlen":1},"id":26,"type":"obj","desc":"ov_cr\\uff1a\\u8fc7\\u6d41\\u4fdd\\u62a4"}]',
    },
  },

==
2. Lonsonho Wifi Smart Plug (metered with RGBW)
  {
    name: 'Plug ',
    id: 'xxxxxxxxxxxxxx',
    key: 'yyyyyyyyyyyyy',
    def: {
      schema: '[{"mode":"rw","code":"led_switch","name":"\\u5f00\\u5173","property":{"type":"bool"},"id":1,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","scene_1","scene_2","scene_3","scene_4"],"type":"enum"},"id":2,"type":"obj","desc":""},{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6","property":{"unit":"","min":25,"max":255,"scale":0,"step":1,"type":"value"},"id":3,"type":"obj","desc":""},{"mode":"rw","code":"temp_value","name":"\\u51b7\\u6696","property":{"unit":"","min":0,"max":255,"scale":0,"step":1,"type":"value"},"id":4,"type":"obj","desc":""},{"mode":"rw","code":"colour_data","name":"\\u5f69\\u5149\\u6a21\\u5f0f\\u6570","property":{"type":"string","maxlen":14},"id":5,"type":"obj","desc":"rgbhsv"},{"mode":"rw","code":"scene_data","name":"\\u60c5\\u666f\\u6a21\\u5f0f\\u6570","property":{"type":"string","maxlen":14},"id":6,"type":"obj","desc":"rgbhsv"},{"mode":"rw","code":"flash_scene_1","name":"\\u67d4\\u5149\\u6a21\\u5f0f","property":{"type":"string","maxlen":14},"id":7,"type":"obj","desc":""},{"mode":"rw","code":"flash_scene_2","name":"\\u7f24\\u7eb7\\u6a21\\u5f0f","property":{"type":"string","maxlen":44},"id":8,"type":"obj","desc":""},{"mode":"rw","code":"flash_scene_3","name":"\\u70ab\\u5f69\\u6a21\\u5f0f","property":{"type":"string","maxlen":14},"id":9,"type":"obj","desc":""},{"mode":"rw","code":"flash_scene_4","name":"\\u6591\\u6593\\u6a21\\u5f0f","property":{"type":"string","maxlen":44},"id":10,"type":"obj","desc":""},{"mode":"rw","code":"power","name":"power","property":{"type":"bool"},"id":101,"type":"obj","desc":"\\u63d2\\u5ea7\\u5f00\\u5173"},{"mode":"rw","code":"countdown","name":"\\u5ef6\\u8fdf","property":{"unit":"S","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"id":102,"type":"obj","desc":""},{"mode":"ro","code":"add_ele","name":"\\u7535\\u91cf","property":{"unit":"\\u5ea6","min":0,"max":500000,"scale":3,"step":100,"type":"value"},"id":103,"type":"obj","desc":"\\u4e0a\\u62a5\\u7684\\u4e3a\\u653e\\u5927100\\u500d\\u4e4b\\u540e\\u7684\\u503c\\uff0c\\u5373\\u4e0a\\u62a556\\uff0c\\u5b9e\\u9645\\u503c\\u4e3a0.56\\u5ea6"},{"mode":"ro","code":"cur_current","name":"\\u7535\\u6d41","property":{"unit":"mA","min":0,"max":30000,"scale":0,"step":1,"type":"value"},"id":104,"type":"obj","desc":""},{"mode":"ro","code":"cur_power","name":"\\u529f\\u7387","property":{"unit":"W","min":0,"max":50000,"scale":0,"step":1,"type":"value"},"id":105,"type":"obj","desc":""},{"mode":"ro","code":"cur_voltage","name":"\\u7535\\u538b","property":{"unit":"V","min":0,"max":2500,"scale":0,"step":1,"type":"value"},"id":106,"type":"obj","desc":""}]',
      extras: '[{"id":1,"inputStyle":"","inputType":" "},{"id":2,"inputStyle":"","inputType":" "},{"id":3,"inputStyle":"","inputType":" "},{"id":4,"inputStyle":"","inputType":" "},{"id":101,"inputStyle":"","inputType":" "},{"id":102,"inputStyle":"","inputType":" "},{"id":103,"inputStyle":"","inputType":""},{"id":104,"inputStyle":"","inputType":""},{"id":105,"inputStyle":"","inputType":""},{"id":106,"inputStyle":"","inputType":""}]',
    },
  },

![IMG_7601](https://user-images.githubusercontent.com/61165387/74692301-ada0f400-51f7-11ea-93ae-68e036aff395.jpeg)

**Comment by bushshrub** [comment]
Can confirm that Ucomen home still works. I believe the TuyaSmart app was updated and uses a different method which can't be intercepted by the proxy anymore

**Comment by bushshrub** [comment]
As of today, Ucomen home no longer works.

**Comment by funtik039** [comment]
Have any new options to keys?

**Comment by kalety** [comment]
CocoonConnect still works!, anda Alexa compatible...

**Comment by chinloon** [comment]
Yes, confirmed that CocoonConnect still works.  Download and prevent it from autoupdate.
