### ISSUE TITLE
Failed to discover

### ISSUE THREAD

**Issue by twistedindustries** [AMoo-Miki/homebridge-tuya-lan#15]
I am coming from the homebridge-tuya plugin which I had working just fine.  When I try to configure this plugin I get "Failed to discover Hallway Light (80881651840d8e539137) in time but will keep looking."  I can't get the device to show up at all.  Here is a copy of my config file:

`{
  "bridge": {
    "name": "Homebridge",
    "username": "0C:2B:3B:C9:FA:0C",
    "port": 46385,
    "pin": "048-67-101"
  },
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "platforms": [
    {
      "platform": "TuyaLan",
      "devices": [
        {
          "name": "Hallway Light",
          "type": "Outlet",
          "manufacturer": "Cotify",
          "model": "Smart Wifi Bulb Socket E26",
          "id": "80881651840d8e539137",
          "key": "fc27ee198e967e13"
        }
      ]
    }
  ]
}
`

**Comment by twistedindustries** [comment]
I was able to resolve this by removing and adding some of my devices in the tuya app.

**Comment by miltykiss** [comment]
@twistedindustries I'm also receiving this issue. To clarify, do you mean that you removed and readded devices in the Tuya app on your phone?

**Comment by twistedindustries** [comment]
@miltykiss Yes to clarify further, I removed the device from the Tuya app and then readded them.  You'll have to run the setup again because the key will have changed.  For good measure I also changed the pin and username in my config and deleted /persist and /accessories folders.  After taking those steps my setup has been stable so far.  Hope that helps

**Comment by miltykiss** [comment]
I completely forgot about this and randomly remembered. I tried what you did (including changing the pin/username as well as deleted the persist and accessories folders) and it still fails to discover. :(

**Comment by jesusdp** [comment]
> @miltykiss Yes to clarify further, I removed the device from the Tuya app and then readded them. You'll have to run the setup again because the key will have changed. For good measure I also changed the pin and username in my config and deleted /persist and /accessories folders. After taking those steps my setup has been stable so far. Hope that helps

@miltykiss do you know if you did the followed steps using the proxy configuration from the setup instructions or just normal to readded them as a normal process? Thanks.

**Comment by miltykiss** [comment]
I did the steps with the proxy configuration.
