### ISSUE TITLE
Add a device type

### ISSUE THREAD

**Issue by soaringsoul** [AMoo-Miki/homebridge-tuya-lan#16]
I purchased a smart dimmable light switch from amazon. 
https://www.amazon.com/gp/product/B07K67D43J/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

The signature of my switch is as follows:

`Ready to handle Light with signature {"1":true,"2":255}`

**Comment by twistedindustries** [comment]
I took the time to add this tonight.  Created an issue as I don't know the proper way of sharing my code.  Here is the issue: https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/19

**Comment by AMoo-Miki** [comment]
Thanks @twistedindustries.

@soaringsoul, while I have pushed the changes to the repository, I have not made a release yet. To update the plugin and play with the `SimpleDimmer`, run `npm i -g AMoo-Miki/homebridge-tuya-lan`

```json5
{
  "name": "The Light",
  "type": "SimpleDimmer",
  "manufacturer": "TESSAR",
  "model": "Smart Dimmer",
  "id": "xxxxx",
  "key": "xxxxxx"
}
```
