### ISSUE TITLE
"Socket had a problem and will reconnect" after RGBTW lamp is turned off, then back on

### ISSUE THREAD

**Issue by jnuk** [AMoo-Miki/homebridge-tuya-lan#173]
Hey, I have a problem with my RGBTW lamp after I turn it off using the power switch (like you would with a normal lamp). I'm using 1.5.0-rc.12. When I turn the lamp off, obviously tuya-lan loses connection and tries to reconnect and therefor spams the homebridge.log with `[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)`
First question: is there a way to disable the retries after a certain time or number of tries and wait for the next UDP packet from the lamp instead?

Now my second problem is that if I turn the lamp back on using the power switch, it seems like tuya-lan tries to reconnect to the lamp, but fails for some reason.
The lamp is powered on and homebridge just started, so all is working normally:
```
[TuyaAccessory] Sending Küche Deckenlampe {"22":1000}
[TuyaAccessory] Sending Küche Deckenlampe {"20":true}
[TuyaAccessory] Heard back from Küche Deckenlampe with command 8
[TuyaAccessory] Heard back from Küche Deckenlampe with command 8
```
Now I turn the lamp off using the switch.
```
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
```
Again, this seems normal to me, but this would soon turn into these error messages filling up the log file. Now I turn the lamp back on and would expect it to become available again, but various errors occur:
```
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (ECONNREFUSED)
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Heard back from Küche Deckenlampe with command 10
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Heard back from Küche Deckenlampe with command 10
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
...
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (ECONNRESET)
...
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
...
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (ECONNRESET)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EALREADY)
[TuyaDiscovery] UDP from 192.168.178.30:6667 0x000055aa...0x0000aa55
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Heard back from Küche Deckenlampe with command 10
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EPIPE)
[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (ECONNRESET)
```
and so on... If needed, I can provide the whole log file.
If I restart homebridge, everything is working fine again and the lamp is working properly.
```
[TuyaDiscovery] Discovery started on port 6666.
[TuyaDiscovery] Discovery started on port 6667.
[TuyaDiscovery] UDP from 192.168.178.30:6667 0x000055aa...0x0000aa55
[2020-2-29 10:10:09 PM] [TuyaLan] Discovered Küche Deckenlampe (<id>) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for Küche Deckenlampe to 9s
[2020-2-29 10:10:09 PM] [TuyaLan] Connected to Küche Deckenlampe
[TuyaAccessory] Sending first query to Küche Deckenlampe (3.3)
[TuyaAccessory] Heard back from Küche Deckenlampe with command 10
[2020-2-29 10:10:10 PM] [TuyaLan] Ready to handle Küche Deckenlampe (RGBTWLight:3.3) with signature {"20":true,"21":"colour","22":1000,"23":579,"24":"0000000003e8","25":"000e0d0000000000000000c80000","26":0}
```

My homebridge config.json looks like this:
```json
{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Küche Deckenlampe",
            "type": "RGBTWLight",
            "manufacturer": "Oeegoo",
            "model": "YY-CL16-220S-WF(RGB+)",
            "id": "<id>",
            "key": "<key>",
            "dpPower": 20,
            "dpMode": 21,
            "dpBrightness": 22,
            "dpColorTemperature": 23,
            "dpColor": 24,
            "minWhiteColor": 140,
            "maxWhiteColor": 400,
            "colorFunction": "HSB"
        }
    ]
}
```
Thanks for your help!

**Comment by jnuk** [comment]
I was able to somewhat solve this issue by adding
```
"pingTimeout": 2147483,
"connectTimeout": 2147483,
```
to the device config. Now when I turn the lamp off, I still get
`[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)`
every few seconds, but it recovers fine when I turn the power back on. 2147483000 ms should last me approx. 25 days, which should be plenty, so I‘m closing this issue for now.

**Comment by Faisalthe01** [comment]
> I was able to somewhat solve this issue by adding
> 
> ```
> "pingTimeout": 2147483,
> "connectTimeout": 2147483,
> ```
> 
> to the device config. Now when I turn the lamp off, I still get
> `[TuyaAccessory] Socket had a problem and will reconnect to Küche Deckenlampe (EHOSTUNREACH)`
> every few seconds, but it recovers fine when I turn the power back on. [2147483000](tel:2147483000) ms should last me approx. 25 days, which should be plenty, so I‘m closing this issue for now.

Thank you. You solved one of my big problem

**Comment by jeylites** [comment]
I'm not sure what is wrong with my setup,I have two problems first I get the same connection error timeout. After adding your findings it has went away but my GU10 RGBAW bulb show up as a regular bulb on homekit 

```
{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "wifi+BLE",
                    "type": "RGBTWLight",
                    "manufacturer": "MOKO",
                    "model": "wifi+BLE Smart bulb",
                    "id": "17088888888",
                    "key": "17088888888",
                    "ip": "192.168.1.101",
                    "dpPower": 20,
                    "dpMode": 21,
                    "dpBrightness": 22,
                    "dpColorTemperature": 23,
                    "dpColor": 24,
                    "minWhiteColor": 140,
                    "maxWhiteColor": 400,
                    "colorFunction": "HSB",
                    "pingTimeout": 2147483,
                    "connectTimeout": 2147483
}
```

**Comment by jeylites** [comment]
here is my logs

```
[10/1/2020, 18:39:10] Homebridge v1.2.3 is running on port 51155.
[10/1/2020, 18:39:11] [TuyaLan] Unregistering wifi+BLE
[10/1/2020, 18:40:10] [TuyaLan] Failed to discover wifi+BLE (################) in time but will connect via 192.168.1.101.
[10/1/2020, 18:40:10] [TuyaLan] Connected to wifi+BLE
[TuyaAccessory] Disconnected from wifi+BLE
[TuyaAccessory] Closed connection with wifi+BLE
```

**Comment by jnuk** [comment]
> I'm not sure what is wrong with my setup,I have two problems first I get the same connection error timeout. After adding your findings it has went away but my GU10 RGBAW bulb show up as a regular bulb on homekit 
> 
> 
> 
> ```
> 
> {
> 
>             "platform": "TuyaLan",
> 
>             "devices": [
> 
>                 {
> 
>                     "name": "wifi+BLE",
> 
>                     "type": "RGBTWLight",
> 
>                     "manufacturer": "MOKO",
> 
>                     "model": "wifi+BLE Smart bulb",
> 
>                     "id": "17088888888",
> 
>                     "key": "17088888888",
> 
>                     "ip": "192.168.1.101",
> 
>                     "dpPower": 20,
> 
>                     "dpMode": 21,
> 
>                     "dpBrightness": 22,
> 
>                     "dpColorTemperature": 23,
> 
>                     "dpColor": 24,
> 
>                     "minWhiteColor": 140,
> 
>                     "maxWhiteColor": 400,
> 
>                     "colorFunction": "HSB",
> 
>                     "pingTimeout": 2147483,
> 
>                     "connectTimeout": 2147483
> 
> }
> 
> ```

Maybe try taking out all the parameters for the pin numbers (dpPower etc.) and color settings. These just apply to my specific lamp and are probably different for yours.
Also check if RGBTWLight is the correct type for your lamp. There's a list of all types in the wiki.

**Comment by jeylites** [comment]
@jnuk are there any documentation on how to setup DpPower? Type: RGBTWLight is correct. How did you manage to find the right settings for you bulb or downlight?

**Comment by jnuk** [comment]
If I remember correctly, I googled the light's name and found the settings in one of the issues on this repo. I don't think there is a guide and as long as you don't have access to the schematics of your lamp or someone else has found out the correct pins, you might have to find it out yourself by trial and error...
