### ISSUE TITLE
Add dimmer

### ISSUE THREAD

**Issue by twistedindustries** [AMoo-Miki/homebridge-tuya-lan#19]
I've added dimmer functionality and would like to add to this repo, what's the best way to do that?

**Comment by twistedindustries** [comment]
I created a commit for it here: https://github.com/twistedindustries/homebridge-tuya-lan/commit/3709e0f306190a2a773610de7c094680185aba2d

**Comment by andrewlove1** [comment]
What "type" should I use for a dimmable light?

**Comment by twistedindustries** [comment]
@andrewlove1 if you are using my code you would use "DimmerLight"

**Comment by twistedindustries** [comment]
hmm you might have to fully remove the device and re-add it if you've had it in homebridge before.  I know I've had issues with devices using this plugin until I do a factory reset on the device and re-add it to homebridge

**Comment by andrewlove1** [comment]
I downloaded your code and used DimmerLight as the type and when I started homebride it said type not valid. Any reason that could be happening?

**Comment by twistedindustries** [comment]
sounds like my code is missing from somewhere, you got the changes in ./index.js right?

**Comment by AMoo-Miki** [comment]
I'll include it in the plugin. Thanks. :)

**Comment by AMoo-Miki** [comment]
Thanks @twistedindustries.

While I have pushed the changes to the repository, I have not made a release yet. To update the plugin and play with the `SimpleDimmer`, run `npm i -g AMoo-Miki/homebridge-tuya-lan`

```json5
{
  "name": "The Light",
  "type": "SimpleDimmer",
  "manufacturer": "TESSAR",
  "model": "Smart Dimmer",
  "id": "xxxxx",
  "key": "xxxxxx"
}
```

**Comment by Sefaal** [comment]
Everything works in terms of turning on the dimmer switch and being able to use the dimming feature on my iPhone. the only thing is that the lights still don't dim at all.
Can anyone point me in the right direction to be able to get this feature to work?

**Comment by twistedindustries** [comment]
> Everything works in terms of turning on the dimmer switch and being able to use the dimming feature on my iPhone. the only thing is that the lights still don't dim at all.
> Can anyone point me in the right direction to be able to get this feature to work?

This may seem like a stupid question, but your using dimmable bulbs right?  In other words, your able to dim with the switch, correct?  I'm using this code and use my dimmer everyday.

**Comment by Sefaal** [comment]
Yes the bulbs are dimmable LED and I can dim them no problem directly from the switch on the wall.

**Comment by twistedindustries** [comment]
Thought so.  Are you seeing any errors in your log?  Can you post your log showing what the switch is sending?  It is possible your switch uses a different protocol than mine.

**Comment by Sefaal** [comment]
stupid question... kinda new at this. Where are the logs for homebridge. I'm running homebridge on a raspberry pi with raspbian light as my OS.

**Comment by Sefaal** [comment]
here are my logs that I could find.
Apr 02 16:20:00 wwhub homebridge[1974]: [2019-4-2 16:20:00] [TuyaLan] Discovered Basement Lights (53365228807d3a706399)
Apr 02 16:20:00 wwhub homebridge[1974]: [TuyaAccessory] Discovery ended.
Apr 02 16:20:00 wwhub homebridge[1974]: [2019-4-2 16:20:00] [TuyaLan] Connected to Basement Lights
Apr 02 16:20:00 wwhub homebridge[1974]: [2019-4-2 16:20:00] [TuyaLan] Ready to handle Basement Lights with signature {"1":false,"3":255}

And here are logs of changing the percentage for the dimming.
Apr 02 16:43:41 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":87}
Apr 02 16:43:41 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:42 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":124}
Apr 02 16:43:42 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:44 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":172}
Apr 02 16:43:44 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:44 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":195}
Apr 02 16:43:44 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:44 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":197}
Apr 02 16:43:47 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":246}
Apr 02 16:43:47 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:47 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":255}
Apr 02 16:43:47 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:49 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":197}
Apr 02 16:43:49 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":142}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":119}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":117}
Apr 02 16:43:50 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:53 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":87}
Apr 02 16:43:53 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:53 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":78}
Apr 02 16:43:53 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:55 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":172}
Apr 02 16:43:55 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:55 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":195}
Apr 02 16:43:55 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:57 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":131}
Apr 02 16:43:57 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:57 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":32}
Apr 02 16:43:57 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":true}
Apr 02 16:43:58 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"2":25}
Apr 02 16:43:58 wwhub homebridge[1974]: [TuyaAccessory] Sending Basement Lights {"1":false}

Please let me know. Thank you.

**Comment by AMoo-Miki** [comment]
Your dimmer is using a different key for brightness; it is `3` instead of `2`. Is this just a dimmable bulb or is a dimmer switch? 

PS, you would be better off opening a new issue with some details about your device and the log you posted above; that way I won't forget to handle your device.

**Comment by Sefaal** [comment]
Thank you @AMoo-Miki for the reply. I will definitely open an new issue for this.

**Comment by AMoo-Miki** [comment]
@Sefaal see #37.
