### ISSUE TITLE
Is this plug-in now depreciated?

### ISSUE THREAD

**Issue by codyc1515** [AMoo-Miki/homebridge-tuya-lan#191]
Looks like https://github.com/iRayanKhan/homebridge-tuya/issues is still being updated, but this repo is not.

**Comment by jamie-2bit** [comment]
I've tried all of them, non are working at the moment due to none of the apps being able to provide the ID and Key.

**Comment by shanelilley** [comment]
> I've tried all of them, non are working at the moment due to none of the apps being able to provide the ID and Key.

Same for me. Even with Ucomen app I cannot get any relevant information.

**Comment by codyc1515** [comment]
Use the Grid Connect app. It still works, for now.

**Comment by muratcorlu** [comment]
I got id & key via tuya-cli with "SmartLink" method described here: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md#linking-a-tuya-device-with-smart-link

First method can also work. You can try it.

**Comment by codyc1515** [comment]
No response in some months. I'm going to move away from this plugin as it seems to be not supported anymore.
