### ISSUE TITLE
Everything’s seems to be ok but not working

### ISSUE THREAD

**Issue by Ie0nard0** [AMoo-Miki/homebridge-tuya-lan#20]
Hi! After a few hours trying to configure the plugin I had managed to put 2 of my outlets plugs in the Home app and when I touch the icon it says that it’s on or off but nothing happens. HomeKit thinks that is turning on/off the plug but the plug is not powering on or off. This is my config.json:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "Hyperion",
            "autoupdate": "true",
            "name": "Tira led",
            "ambilightName": "Tira led",
            "host": "192.168.1.132",
            "port": "19444"
        }
    ],
    "platforms": [
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Camara",
                    "type": "Outlet",
                    "manufacturer": "Tuya",
                    "model": "Outlet Socket SP22",
                    "id": "51817282c44f338021ab",
                    "key": "66e5d96763a624f1"
                },
                {
                    "name": "Termo",
                    "type": "Outlet",
                    "manufacturer": "Tuya",
                    "model": "Outlet Socket SP22",
                    "id": "51817282840d8e5f3d09",
                    "key": "52aae2cb791a341b"
                }
            ]
        },
        {
            "platform": "UPnP",
            "ssdpClient": {
                "interfaces": [
                    "br0"
                ]
            },
            "ssdpServer": {
                "interfaces": [
                    "br0"
                ]
            }
        },
        {
            "platform": "ChuangmiIRPlatform",
            "hidelearn": false,
            "learnconfig": {
                "ip": "192.168.1.141",
                "token": "a42736571fd05d44c2c31ffe81df2fcc"
            },
            "deviceCfgs": [
                {
                    "type": "Custom",
                    "ip": "192.168.1.141",
                    "token": "a42736571fd05d44c2c31ffe81df2fcc",
                    "Name": "test",
                    "interval": 1,
                    "data": {
                        "on": "Z6XNAH4BAADKAQAA0QQAAB0FAADqGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEB",
                        "off": "Z6XNAKkBAADzBAAA5xsAAAkcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARABARAQEBAQECEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAQEBAQEDEBARABARAA"
                    }
                },
                {
                    "type": "MomentarySwitch",
                    "ip": "192.168.1.141",
                    "token": "a42736571fd05d44c2c31ffe81df2fcc",
                    "Name": "Ventilador",
                    "data": "Z6XNAH4BAADKAQAA0QQAAB0FAADqGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEhISEhIUMDAyEDAyEB"
                }
            ]
        }
    ]
}

**Comment by twistedindustries** [comment]
I've detailed this in a few other places but try removing the devices from the tuya app and readding them generating a new key.  Then delete /persist and /accessories from homekit while changing your pin and user name in the config.  That should make your devices work.

**Comment by Ie0nard0** [comment]
Suddenly starts working without do anything. Thanks

**Comment by AMoo-Miki** [comment]
The latest code changes, that havn't made it to the release yet, solve this issue. A release will come in a week until I have had a chance to test all the new features and collect feedback. Until then, if you need to, you can get the latest changes by running `npm i -g AMoo-Miki/homebridge-tuya-lan`.

Good luck.
