### ISSUE TITLE
SimpleBlinds not connecting

### ISSUE THREAD

**Issue by AnonymousPea** [AMoo-Miki/homebridge-tuya-lan#205]
I have just brought the Kogan Blind Driver (https://www.kogan.com/au/buy/kogan-smarterhome-smart-blinds-driver/) and after quite a few attempts and factory resets I managed to get it connected to the tuya app and all is working fine there. 

The issues I am having is I have added it to homebridge, and it shows as an accessory and the status is open, but when I click close (in homebrigde or homekit) it sayings closing and loads to do so but then does nothing, the blind doesn't move. Occasionally homekit will say some random percentages such as 63% closed, but the blind does not move at all and just stays open. 

I have tried this multiple times in the tuya app and it works perfectly fine opening and clothing it from there, the issues to open and close only arises in homebrigde and homekit. 

I have also tried this with the tuya app open in the background and the tuya app closed, and same issue both items.

**Comment by vijaydembla1** [comment]
Hi,
Did you have any luck with this? I have the same issue and struggling to get this fixed.

**Comment by AnonymousPea** [comment]
I ended up using the Tuya Web plug in instead, at least they got connected that way and actually open and close. 
https://github.com/milo526/homebridge-tuya-web

There is an issue with that plug in with the blinds status staying on opening and closing but at least it does open and close them.
