### ISSUE TITLE
Add support for TeePao Blinds (Rollos) integrated wall switch

### ISSUE THREAD

**Issue by produdegr** [AMoo-Miki/homebridge-tuya-lan#22]
Pls add support for TeePao Blinds (Rollos) integrated wall switch.
The name is "TeePao Rollo Switch".
The signature is {"1":"1"}
A link to the device is: https://www.amazon.de/gp/product/B07H9P57SZ/ref=ppx_yo_dt_b_asin_title_o08_s02?ie=UTF8&psc=1

The wall switch is in fact a 2 relay switch. When you switch, it will set to on for approximately 3 minutes (one button up and one button down). The Rollo is cutting the power itself much earlier.
So its fire and forget for up and down.
The middle button (stop), simply cancels one of the above actions.

Trying to implement this in homebridge for 2 months now without any luck, so help would be really appreciated. Willing to give also device id if necessary.
thanks

**Comment by produdegr** [comment]
Don't want to sound demanding and respect-less, 
THANKS for your work on this plugin.

**Comment by AlainKaim** [comment]
Hi
I have the same request for another device, which should work as the Teepao above : Zemismart Curtain Switch
Same signature : Ready to handle Volet Bureau with signature {"1":"1"}

Link to my device : 
http://s.aliexpress.com/yYfAzIfu

Thanks for your work !

**Comment by AMoo-Miki** [comment]
@produdegr you did not sound demanding in any way :) 

I would be more than happy to get this to work for both of you. I will however need your help figuring somethings out. Please update to the latest, unreleased, version of the plugin by running `npm i -g AMoo-Miki/homebridge-tuya-lan` and answer the following questions by examining the logs:

When you press the **open** button on the wall switch, do you see `[TuyaAccessory] SimpleLight changed` **immediately**? If yes, what is the signature it shows?

After you pressed the **open** button on the wall switch and when the blinds are fully open, do you see `[TuyaAccessory] SimpleLight changed`? If yes, what is the signature it shows?

When you press the **close** button on the wall switch, do you see `[TuyaAccessory] SimpleLight changed` **immediately**? If yes, what is the signature it shows?

After you pressed the **close** button on the wall switch and when the blinds are completely closed, do you see `[TuyaAccessory] SimpleLight changed`? If yes, what is the signature it shows?

Do you see any `[TuyaAccessory] SimpleLight changed` during the opening and closing sequences? If yes, what is the signature it shows?

Good luck.

**Comment by produdegr** [comment]
@AMoo-Miki thanks, I tried it remotely from work and the plugin always has same response like:

[TuyaAccessory] Odd message from Blinds with command 8: { cmd: 8,
  data:
   '\f\t\u0004ð%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁYÀ(Nî¢¾zü!y.\u000ba*ï4YG!Í%
YÄ9/hâ®«Î­¦¢SF¡m' }
[TuyaAccessory] Odd message from Blinds with command 8: { cmd: 8,
  data:
   '\f\t\u0004ð%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁu0003ÉZá¨Õ®ÐöÒu`fX¥ëÑRG)ÑÀ;6\nÊÞ©Fb\tJn¿' }

I used the app to do: down and after 1 sec stop command. It pretty much always shows this response.
Looks like the message is encrypted :(

Will do exactly your test when at home this afternoon, by using the wall switch instead and will reply.

**Comment by produdegr** [comment]
PS. I have the device in config like this:
                    "name": "Blinds",
                    "type": "Outlet",
                    "manufacturer": "Teepao",
                    "model": "Teepao Blinds Opener",
                    "id": "50758014840d8e91eabd",
                    "key": "xxxxxxxxxxxxxxxxxx"
,as I was experimenting with it. Will change it to "SimpleLight" also and test.

**Comment by produdegr** [comment]
after changing to "SimpleLight" got on discovery:

[3/14/2019, 5:40:10 PM] [TuyaLan] Discovered Blinds (50758014840d8e91eabd)
[3/14/2019, 5:40:10 PM] [TuyaLan] Blinds has a different type (7 vs 5)
[TuyaAccessory] Discovery ended.
[3/14/2019, 5:40:10 PM] [TuyaLan] Connected to Blinds
[3/14/2019, 5:40:10 PM] [TuyaLan] Ready to handle Blinds with signature {"1":"3"}

And then pressing down, stop and up:

[TuyaAccessory] Odd message from Blinds with command 8: { cmd: 8,
  data:
   "\f\t\u0004ð%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁu0003ÉZá¨Õ®ÐöÒu`!\\Û\u0006NÆºóÁêc¨êNË=\u000bÆH'­çjHZ%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁYÀ(Nî¢¾zü!y\u0017\u0002\u0015²ÖDW\u001b ñ\u001e¬2\u0019`zs;'­
\u0017Z" }
[TuyaAccessory] Odd message from Blinds with command 8: { cmd: 8,
  data:
   '\f\t\u0004ð%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁu0003ÉZá¨Õ®ÐöÒu`Ûa Bçä;¾ØJWa(ìØC ßÎ±u\u0007_q²\u0018¶md' }
[TuyaAccessory] Odd message from Blinds with command 8: { cmd: 8,
  data:
   '\f\t\u0004ð%\u0015Ó\u00199X¨sxÑ­ëÿá\u0019ýr\u0002+éã5.pÁu000bRæ\u00100ì!ð½\u000fgYuÐ:®ÂþDK \u0017\u0001G¦õýWÝüÛl³Úô\u0001n¯¶¡' }

As mentioned will do tests at home as you suggested.

**Comment by AMoo-Miki** [comment]
This means decryption failed. This only happens if (1) the key is not correct or (2) they are using a different encryption algorithm than others. Can you do these in the following order:

1) Remove the device from the Tuya app.
2) Add the device to Tuya app.
3) Follow the [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) to get a new `key`. Lemme know if this doesn't produce a new `key`.
4) Close the Tuya app and don't open it again till we end this experiment.
5) Add the `id` and `key` to the config file and restart Homebridge.
6) Use the physical buttons to trigger changes.

We will need to get rid of `Odd message` problem before we can move forward.

**Comment by produdegr** [comment]
Thanks, will do that tomorow (need to lend me again an android device to get a possible new device key - I don't do android except NVidia Shield hehe).

**Comment by AMoo-Miki** [comment]
My instructions are based on an iPhone; if you follow them you won't need an Android device.

**Comment by produdegr** [comment]
Yep, thanks.
Finally, you were right, the key had changed. Must have removed it and added it sometime without querying for new key.
So now no command 8 messages anymore.

However as "SimpleLight", there is nothing in the log when pressing the buttons or when doing up-stop-down commands via the "SmartLife" app (Tuya Clone).

I did however some further testing:
As "SimpleLight":
- Nothing happens when pressing buttons, no changes of led.
- The following is displayed when starting up homebridge:
[3/16/2019, 11:51:00 AM] [TuyaLan] Discovered Blinds (50758014840d8e91eabd)
[3/16/2019, 11:51:00 AM] [TuyaLan] Blinds has a different type (7 vs 5)
[TuyaAccessory] Discovery ended.
[3/16/2019, 11:51:00 AM] [TuyaLan] Connected to Blinds
********************If blind are already down position:
[3/16/2019, 11:52:57 AM] [TuyaLan] Ready to handle Blinds with signature {"1":"1"}
********************If blinds are already up position:
[3/16/2019, 11:47:28 AM] [TuyaLan] Ready to handle Blinds with signature {"1":"2"}

As "MultiOutlet" with "outletCount" : 3 I got same as above, but when pressing on homwbridge accessories "Outlet 1" the upper LED lights up - however without movement.

So, what I understand is that we got 3 switches with 3 different states Up, DOWN and PAUSED (the middle button).

The test you requested to see if something is logged, I repeat that no message is shown in the log.

Please tell me anything else to test if needed.

Thank You for your time and help.

**Comment by produdegr** [comment]
PS. when pressing ON via homebridge, no action but:
[TuyaAccessory] Sending Blinds {"1":true}
[TuyaAccessory] Socket had a problem and will reconnect to Blinds (ECONNRESET)
[TuyaAccessory] Closed connection with Blinds

thanks

**Comment by produdegr** [comment]
@AMoo-Miki about this integration, I know that Apple Homekit handless the "blinds" differently, so could it be done by splitting the device in 2 or 3 virtual ones (Open, Close and Pause) as simple switches?
This would make it work I believe, because the command is only simply issued to the cloud without any feedback regarding the state of the blinds, except of open, close and pause.

Just an idea, you should have more experience with this. 
Thanks.

**Comment by produdegr** [comment]
I tested therefore this:

                {
                    "name": "Blinds",
                    "type": "CustomMultiOutlet",
                    "manufacturer": "Teepao",
                    "model": "Teepao Blinds Opener",
                    "id": "50758014840d8e91",
                    "key": "xxxxxxxxxxxxxxxxxx",
                    "outlets": [
                        {
                            "name": "Blinds Open",
                            "dp": 1
                        },
                        {
                            "name": "Blinds Close",
                            "dp": 2
                        },
                        {
                            "name": "Blinds Pause",
                            "dp": 3
                        }
                    ]
                }
This is what we need, except that it must send integer values, rather than true or false (I believe this is the reason why the device reboots).
Don't know if 1,2,3 must be send to parameter 1 only or to parameters 1,2,3.
Thanks

**Comment by AlainKaim** [comment]
No pressure but I have just ordered  7 more curtain switches. 
So I will have be happy if you find a way to support them!
(And if not, no problem)

**Comment by AMoo-Miki** [comment]
Working on it right now.

**Comment by AMoo-Miki** [comment]
I have a preliminary version for you to mess with and give feedback. Please update the plugin using `npm i -g AMoo-Miki/homebridge-tuya-lan` and restart Homebridge.

Define your device similar to this:
```json
{
    "name": "<a nice name>",
    "type": "SimpleBlinds",
    "manufacturer": "Teepao",
    "model": "Teepao Blinds Opener",
    "id": "<the id>",
    "key": "<the key>",
    "duration": 30
}
```

Change the duration to how long it takes to fully open from closed state, in seconds. When you use Home to open the blinds halfway, since the opener doesn't inform us about its position, I have done some math to figure it out based on how long it takes for it to hear back from the device. Considering network latency and the opener's response speed, there is no way to accurately measure this; in my tests it was at best 3% off and at worst 15% off. Lemme know how that effects you and I will think of some ways to make it more predictable.

Best of luck.

**Comment by AlainKaim** [comment]
How great , thanks !
I will play with it tonite 
Have a nice day.

--
Proudly sent from my iPad Pro!

**Comment by produdegr** [comment]
Great, will test as well.
Thanks!

**Comment by produdegr** [comment]
I'm not at home, but I did test the messaging using the official tuya app (pressed close, then pause, then up):
[TuyaAccessory] Blinds will be marked closed in 15000ms
[TuyaAccessory] Blinds last change was 1554704336562; 19563ms ago
[TuyaAccessory] Blinds marked stopped at 0
[TuyaAccessory] Blinds will be marked open in 15000ms
[TuyaAccessory] Blinds marked open
I thing it looks nice. Will check actual blinds by using homekit when home.
Thanks again.

**Comment by AlainKaim** [comment]
I was so eager to test it, that I have delayed my morning home departure for 10 minutes....
In short, it works for basic use : blinds open and close, and status on Home app is coherent.
Thanks for this !
More tests tonight : change to Duration,  partial opening, ....

**Comment by AMoo-Miki** [comment]
I am glad the basics work. By default, I have assumed it takes 15 seconds to open and close the blinds. I would love to set that to a more realistic number.

`19563ms ago` makes me uncomfortable since it almost means there was a 4.5 seconds latency and that will throw off the math drastically. I will wait for you all to play some more and give me your feelings.

**Comment by produdegr** [comment]
First of all THANK YOU,
it works beautifully as it is. I liked the idea of dividing total time that is specified in the config file to emulate the homekit percentage.
If you like to spend more time on this, here are my further tests:
I calculated an average of 32 seconds for my rollos to open and close (pretty close your guess!!!).
So I entered 32 into config.
All tests are from idle (no led is lighting up on wall socket):
When selecting 30% Open in Homekit, my rollos are 80% Open,
When selecting 12% Open in Homekit, my rollos are 40% Open.
If Rollos are moving or wall switch is not idle, moving the slider up or down messes things up (unpredictable), except for setting 100% or 0%, then Rollos Open or Close respectively.
I believe parameter for tweakiing the time would be perfect (like float, where 1 would be no change).
But again, I am Very happy as it is right now, it is perfectly usable.
Thank you

**Comment by AlainKaim** [comment]
Here are the results of my tests with the Zemismart device.


Full opening and closing works really well.
And I can use Siri commands as well :)
Status is ok.


When I tap  on the device in the ap during movement, it stops (which is nice).
When I tap again, it moves in the opposite direction (which makes sense).

—
Partial opening :

My physical duration is about 20s from open to almost closed. 
Plus 4-5s for the last part, when the blind is down, but the motor is still on : this extra time is necessary to tighten the blades.

So I have put 20s in the config file.

On partial closing, it works well :
50% lead to a 40-45% opening.

But on partial opening, it is quite different : 
50% opens only 20% of the blind. I think is is related to the “las part”, when’ the blind does not move up but the motor  untighten the blades.
For my kind of shutter, it would be great to add a latency duration, to take into account this necessary time, note related to the position.

—
One last thing :  when I use partial closing with one tap at the wanted position, the command is correctly interpreted. But when I keep my finger, and then I try to adjust he slider position, the plugin get the wrong command.  And then, the blind and the plugin "assumed position" are out of sync.
Not a big deal, when you know it.

—
As a conclusion, we already have a good working solution : Home gives me much more flexibility than the native app.
Thanks for this great work !

**Comment by AMoo-Miki** [comment]
@produdegr and @AlainKaim, this is great news. I tried to simplify the calculation logic while moving from one half-open to another; please give it a try and let me know how it works.

@produdegr, do your blinds also spend the last couple of seconds to tighten things up?

@AlainKaim, I have introduced a new parameter, `timeToTighten`, to define how long it takes for the tighten the on the closing end. The value of `timeToOpen`  should remain the same as before; it is the duration from dead-closed to full open. Lemme know how it feels.

**Comment by produdegr** [comment]
Hi, great news indeed,
As I have a rollo, there is not tighten happening. But when it reaches either end (fully open or close), the electrical rollo drum switches itself off, so exact timing is not needed.
Will try it, and report back.
Thanks

**Comment by produdegr** [comment]
Sorry for my ignorance, of course is the rollo tighting at the end (otherwise it will remain with all those small peep holes). Sorry did not get it before.
I will test this new setting as well.
Thanks

**Comment by AMoo-Miki** [comment]
I forgot to mention that you will need to update the plugin to the latest code with `npm i -g AMoo-Miki/homebridge-tuya-lan` and restart Homebridge.

**Comment by produdegr** [comment]
Did that. I also did a test remotely:
The Rollo was open and clicked on 49%. So rollo went almost to the end - not 49%, but i can fix that by analogue the time. Then pressed to go to 26% and it went all to the end plus tightening. Then up. The log for the second step (first one did not have log file open sorry):
My settings are:
                    "duration": 32,
                    "timeToTighten": 5  (aprox)
[TuyaAccessory] Blinds asked to move from 48.904444444444444 to 26
[TuyaAccessory] Sending Blinds {"1":"2"}
[TuyaAccessory] Blinds will stop in 10307ms
[TuyaAccessory] Blinds assumed started 1555582138752; 22993ms ago
[TuyaAccessory] Saw change to 2
[TuyaAccessory] Blinds asked to stop
[TuyaAccessory] Sending Blinds {"1":"3"}
[TuyaAccessory] Saw change to 3
[TuyaAccessory] Blinds last change was 1555582138752; 33334ms ago
[TuyaAccessory] Blinds marked stopped at 26; assumed to be at 25.922222222222217
[TuyaAccessory] Blinds asked to move from 25.922222222222217 to 88
[TuyaAccessory] Sending Blinds {"1":"1"}
[TuyaAccessory] Blinds will stop in 27935ms
[TuyaAccessory] Blinds assumed started 1555582160669; 17065ms ago
[TuyaAccessory] Blinds asked to move from 25.922222222222217 to 100
[TuyaAccessory] Blinds opening had started 1555582160669; 17083ms ago
[TuyaAccessory] Blinds' adjusted assumedPosition is 25.962222222222223
[TuyaAccessory] Sending Blinds {"1":"1"}
[TuyaAccessory] Saw change to 1
[TuyaAccessory] Blinds will be marked open in 33317ms

Will test further when at home (my son gave feedback now).
I think it looks very nice!
Thanks

**Comment by AlainKaim** [comment]
Hi,
I think there is a mistake in your logic : I asked to open the blinde à 29%, and it moved up to 70%

Then, I opened it. And asked to close it at 29% : it moved all the way down, until fully closed
My settings are : 
`"duration": 22,
  "timeToTighten" : 5`
Here is the log : 
`[TuyaAccessory] Blinds asked to move from -12 to 29
[TuyaAccessory] Sending Volet antichambre {"1":"1"}
[TuyaAccessory] Blinds will stop in 18450ms
[TuyaAccessory] Blinds assumed started 1555610032041; 0ms ago
[TuyaAccessory] Saw change to 1
[TuyaAccessory] Blinds asked to stop
[TuyaAccessory] Sending Volet antichambre {"1":"3"}
[TuyaAccessory] Saw change to 3
[TuyaAccessory] Blinds last change was 1555610032041; 18491ms ago
[TuyaAccessory] Blinds marked stopped at 29; assumed to be at 29.09111111111111
[TuyaAccessory] Blinds asked to move from 29.09111111111111 to 100
[TuyaAccessory] Sending Volet antichambre {"1":"1"}
[TuyaAccessory] Saw change to 1
[TuyaAccessory] Blinds will be marked open in 31909.000000000007ms
[TuyaAccessory] Blinds marked open
[TuyaAccessory] Blinds asked to move from 100 to 29
[TuyaAccessory] Sending Volet antichambre {"1":"2"}
[TuyaAccessory] Blinds will stop in 31950ms
[TuyaAccessory] Blinds assumed started 1555610230422; 0ms ago
[TuyaAccessory] Saw change to 2
[TuyaAccessory] Blinds asked to stop
[TuyaAccessory] Sending Volet antichambre {"1":"3"}
[TuyaAccessory] Saw change to 3
[TuyaAccessory] Blinds last change was 1555610230422; 31996ms ago
[TuyaAccessory] Blinds marked stopped at 29; assumed to be at 28.897777777777776
`
Then I asked it to be closed, and then open again at 78%.
It moved all the way up....

I have also tried with a shorter duration (17s), but I was unable to understand the logic: moves are never consistent with my orders.

If you need some specific testing, just ask.

**Comment by produdegr** [comment]
Unfortunately same thing here:
from 100% open pressed to close to 50% open: moves rollo to 10% (almost close)
from 100% open pressed to close to 65% open: moves rollo to 20% (almost close)
when fully closed (0% open) pressing to open to 50% open does not do anything.
pressing 100% open, however opens it fully.
Tested these with my updated setting duration: 25, timeToTighten: 5.

Then I changed the settings to 12, timeToTighten: 2. and all result are the same (touched it at 49%).:

[TuyaAccessory] Blinds asked to move from 100 to 49
[TuyaAccessory] Sending Blinds {"1":"2"}
[TuyaAccessory] Blinds will stop in 22950ms
[TuyaAccessory] Blinds assumed started 1555612924057; 0ms ago
[TuyaAccessory] Saw change to 2
[TuyaAccessory] Blinds asked to stop
[TuyaAccessory] Sending Blinds {"1":"3"}
[TuyaAccessory] Saw change to 3
[TuyaAccessory] Blinds last change was 1555612924057; 22968ms ago
[TuyaAccessory] Blinds marked stopped at 49; assumed to be at 48.96

I specified 12 sec as duration but app: Blinds will stop in 22950ms which time moves it to 90% aproximately as my rollo needs 25 seconds to close plus 5 to tighten.
So it seems that duration variable is not really used.

Double checked it, saved config, restart and (from 100% open to 50%):
[TuyaAccessory] Blinds asked to move from 100 to 50
[TuyaAccessory] Sending Blinds {"1":"2"}
[TuyaAccessory] Blinds will stop in 22500ms
[TuyaAccessory] Blinds assumed started 1555613489534; 1ms ago
[TuyaAccessory] Saw change to 2
[TuyaAccessory] Blinds asked to stop
[TuyaAccessory] Sending Blinds {"1":"3"}
[TuyaAccessory] Saw change to 3
[TuyaAccessory] Blinds last change was 1555613489534; 22547ms ago
[TuyaAccessory] Blinds marked stopped at 50; assumed to be at 49.89555555555555

As I set it to 12 seconds it should stop after 6 seconds no 22,5 as stated in log, but also in reality.

Hope this helps.
Thank You

**Comment by badnimits** [comment]
@AMoo-Miki you so fine, you so fine  you blow my mind

Works great!  Thank you very much for your work
[https://www.aliexpress.com/item/Tuya-Smart-Life-WiFi-Curtain-Switch-for-Electric-Motorized-Curtain-Blind-Roller-Shutter-Google-Home-Amazon/32974175747.html?spm=a2g0s.9042311.0.0.27424c4dGDtB8j](https://www.aliexpress.com/item/Tuya-Smart-Life-WiFi-Curtain-Switch-for-Electric-Motorized-Curtain-Blind-Roller-Shutter-Google-Home-Amazon/32974175747.html?spm=a2g0s.9042311.0.0.27424c4dGDtB8j)

**Comment by AMoo-Miki** [comment]
@AlainKaim and @produdegr, one you should knock me on my head! The sample config I had posted had an error. The correct keys are `timeToOpen` and `timeToTighten`. Just rename `duration` to `timeToOpen`.

`timeToOpen` is the total time it takes to go from a full open to a full close.
`timeToTighten` is the time it takes to tighten the blinds on closing.

Sorry about that.

@badnimits, I am glad things are working the way you like.

**Comment by AlainKaim** [comment]
This explains the strange behavior on the last days!
Very quick test : feels good. 
More testing tonight. 

Thanks for everything !

-- Sent from my iPhone 7 😄

**Comment by produdegr** [comment]
@AMoo-Miki Excellent! It works just perfect.
Thank you for your time and effort.

**Comment by PierreBrisorgueil** [comment]
Hello, 

https://www.amazon.fr/gp/product/B07RK95NRM/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

this one for me, impossible to connect : 

```
[TuyaLan] Failed to discover Porte Garage (040226832462ab017798) in time but will connect via xx.xx.xx.xx
 [TuyaAccessory] Socket had a problem and will reconnect to Porte Garage (Error: ERR_CONNECTION_TIMED_OUT)
 [TuyaAccessory] Closed connection with Porte Garage
```

I'm stuck on this from two months, someone have an idea ? 
everything still works on your side, or should we re open this issue ? @AlainKaim @produdegr 

```
{
         "platform": "TuyaLan",
         "devices":[
            {
               "name":"Porte Garage",
               "id":"xxxxxx",
               "key":"xxxxxx",
               "type": "SimpleBlinds",
               "ip": "xx.xx.xx.xx",
               "manufacturer": "Teepao",
               "model": "Teepao Blinds Opener",
               "timeToOpen": 30
            }
         ]
}
```
