### ISSUE TITLE
Failed to intercept secure communications. This could happen due to bad CA certificate.

### ISSUE THREAD

**Issue by wlee88** [AMoo-Miki/homebridge-tuya-lan#230]
Followed these instructions down to a tee - https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions

still getting `Failed to intercept secure communications. This could happen due to bad CA certificate.`

(tried multiple times!)

has something changed?

**Comment by quasarj** [comment]
I am getting the same thing, followed all the instructions, tried it multiple times. It looks like maybe there is something wrong with the MITM proxy?

**Comment by wlee88** [comment]
> It looks like maybe there is something wrong with the MITM proxy?

All makes sense now - I found this in the tuyapi [readme]( https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md)

It states
> This method is deprecated because Tuya-branded apps have started to encrypt their traffic in an effort to prevent MITM attacks like this one

**Comment by wlee88** [comment]
@quasarj The instructions from the readme worked!
