### ISSUE TITLE
Have to use Tuya app after each reboot

### ISSUE THREAD

**Issue by lemaygabriel** [AMoo-Miki/homebridge-tuya-lan#30]
Everything works great except for one thing:

Every time homebridge reboot, I have to go in the Tuya app and do a cycle (on/off) for the switch to be recognized again on homebridge.

Anyone else having this issue ?

Thanks !

**Comment by AMoo-Miki** [comment]
This happens when the device doesn't respond to the handshake. What is the device you are using?

There is a way to not wait for the handshake that hasn't been released yet. To try it, run `npm i -g AMoo-Miki/homebridge-tuya-lan`, add `"intro": false` to the definition block on the device in your config file, and restart Homebridge. It would be great to see if the method works for your device or not. The side effect is that the initial state of the device will be unknown but I might be able to find a way to solve that if I am sure this method works.

**Comment by lemaygabriel** [comment]
Hello AMoo, 

I tried, no difference... :( Also, I tried to add a second device with no luck. Only the first one appear on the Homekit app. I tried to remove the bridge and sync it again with no luck... Any idea ? 
Here's my .json: 

{
        "bridge": {
                "name": "HomebridgeSwitch",
                "username": "CC:xx:xx:xx:xx30",
                "port": xxxxx,
                "pin": "xxx-xx-xxx"  },
        "accessories":[],
        "platforms": [
        {
        "platform": "TuyaLan",
        "devices": [{
                "intro": false,
                "name": "Tuya Dimmer Switch Device 1",
                "type": "SimpleLight",
                "manufacturer": "CE Smart",
                "model": "LA-WF3",
                "id": "45412206dcxxxxxxxxxx",
                "key": "fb27a3xxxxxxxxxx" },
{
                "name": "Tuya Dimmer Switch 2",
                "type": "SimpleLight",
                "manufacturer": "CE Smart",
                "model": "LA-WF3",
                "id": "45412206dcxxxxxxxxxx",
                "key": "778d71xxxxxxxxxx"
        }]
}]
}

**Comment by Rantaholic** [comment]
Hi, I was having the same problem after switching to the tuya-lan plugin.
Ubuntu 18.04 server
Homebridge Version 0.4.47
CE Smart plugs LA-WF3 from Costco

I did as you suggested and installed the version you mentioned.
I added “Intro”: false to both my plugs in my config.json
I deleted my accessories and persist folders and removed homebridge from homekit and readded it.
Both plugs added correctly and displayed the correct state 
(I set 1 plug on and 1 off before starting the whole process to verify states were showing correctly)

Both plugs now function correctly, identify the proper state when added and even if the state is manually changed while Homebridge is shutdown it shows the correct state in HomeKit when Homebridge is restarted.

I did notice a socket error occurred in the log after I shut down homebridge, changed the plug state on one plug and started homebridge. 

Here are some of my results:

**After starting homebridge with the main plugin with issue**

Mar 31 23:52:49 dt2 homebridge[3425]: [3/31/2019, 11:52:49 PM] [TuyaLan] Discovered Test Plug 5 (85074677600194xxxxxx)
Mar 31 23:52:49 dt2 homebridge[3425]: [3/31/2019, 11:52:49 PM] [TuyaLan] Connected to Test Plug 5
Mar 31 23:52:50 dt2 homebridge[3425]: [3/31/2019, 11:52:50 PM] [TuyaLan] Discovered Test Plug 4 (85074677600194xxxxxx)
Mar 31 23:52:50 dt2 homebridge[3425]: [TuyaAccessory] Discovery ended.
Mar 31 23:52:50 dt2 homebridge[3425]: [3/31/2019, 11:52:50 PM] [TuyaLan] Connected to Test Plug 4
Mar 31 23:52:50 dt2 homebridge[3425]: [3/31/2019, 11:52:50 PM] [Config] Using Form Authentication
Mar 31 23:52:50 dt2 homebridge[3425]: [3/31/2019, 11:52:50 PM] [Config] Console v3.9.7 is listening on port 8282.
Mar 31 23:53:25 dt2 homebridge[3425]: [3/31/2019, 11:53:25 PM] [TuyaLan] Test Plug 4 - identify
Mar 31 23:53:27 dt2 homebridge[3425]: [3/31/2019, 11:53:27 PM] [TuyaLan] Test Plug 5 - identify

**After turning on each plug in _tuya app_**

Mar 31 23:56:18 dt2 homebridge[3425]: [3/31/2019, 11:56:18 PM] [TuyaLan] Ready to handle Test Plug 4 with signature {"1":true}
Mar 31 23:56:28 dt2 homebridge[3425]: [3/31/2019, 11:56:28 PM] [TuyaLan] Ready to handle Test Plug 5 with signature {"1":true}


**After installing new version per instructions and starting homebridge **

Apr 01 00:33:32 dt2 homebridge[4068]: [4/1/2019, 12:33:32 AM] [TuyaLan] Connected to Test Plug 4
Apr 01 00:33:32 dt2 homebridge[4068]: [4/1/2019, 12:33:32 AM] [TuyaLan] Ready to handle Test Plug 4 with signature {}
Apr 01 00:33:32 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 4: {"cmd":10,"data":{"devId":"85074677600194xxxxxx","dps":{"1":false,"2":0}}}
Apr 01 00:33:33 dt2 homebridge[4068]: [4/1/2019, 12:33:33 AM] [Config] Using Form Authentication
Apr 01 00:33:33 dt2 homebridge[4068]: [4/1/2019, 12:33:33 AM] [Config] Console v3.9.7 is listening on port 8282.
Apr 01 00:33:34 dt2 homebridge[4068]: [4/1/2019, 12:33:34 AM] [TuyaLan] Discovered Test Plug 5 (85074677600194xxxxxx)
Apr 01 00:33:34 dt2 homebridge[4068]: [TuyaAccessory] Discovery ended.
Apr 01 00:33:34 dt2 homebridge[4068]: [4/1/2019, 12:33:34 AM] [TuyaLan] Connected to Test Plug 5
Apr 01 00:33:34 dt2 homebridge[4068]: [4/1/2019, 12:33:34 AM] [TuyaLan] Ready to handle Test Plug 5 with signature {}
Apr 01 00:33:34 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 5: {"cmd":10,"data":{"devId":"85074677600194xxxxxx","dps":{"1":true,"2":0}}}

**After changing state in HomeKit**

Apr 01 00:37:37 dt2 homebridge[4068]: [TuyaAccessory] Sending Test Plug 4 {"1":true}
Apr 01 00:37:37 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 4: {"cmd":7,"data":""}
Apr 01 00:37:37 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 4: {"cmd":8,"data":"3.1dd1ac01231081066jfr93jOMGrJn8XH5MuMDebyQa49TzqtmKdi7+RvqUbxr2GgIatReJCe8uAIISDCHaV3fvCMF6BhxTrK//fFCBMNbFVDh/K2veP0QVRASNBE="}
Apr 01 00:37:38 dt2 homebridge[4068]: [TuyaAccessory] Sending Test Plug 5 {"1":false}
Apr 01 00:37:38 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 5: {"cmd":7,"data":""}
Apr 01 00:37:38 dt2 homebridge[4068]: [TuyaAccessory] Message from Test Plug 5: {"cmd":8,"data":"3.16c29c8d4c36813a7TVdWocuhpTZ91Ja4YlhlmbwDVoE9bd2IxqJMZe1gQKa6qcMb8nLW8szQ0z83829hmbFeWB5EPKrJTq6w3gB+0gZ5gaxa521dkhtSVXvlklk="}

**After shutting down homebridge, changing state on one plug and starting homebridge**

Apr 01 01:05:25 dt2 homebridge[4589]: [TuyaAccessory] Socket had a problem and will reconnect to Test Plug 5 (ECONNRESET)
Apr 01 01:05:25 dt2 homebridge[4589]: [TuyaAccessory] Closed connection with Test Plug 5
Apr 01 01:05:25 dt2 homebridge[4589]: [TuyaAccessory] Message from Test Plug 5: {"cmd":10,"data":{"devId":"85074677600194xxxxxx","dps":{"1":tApr 01 01:05:26 dt2 homebridge[4589]: [4/1/2019, 1:05:26 AM] [TuyaLan] Discovered Test Plug 4 (85074677600194b00715)
Apr 01 01:05:26 dt2 homebridge[4589]: [TuyaAccessory] Discovery ended.
Apr 01 01:05:26 dt2 homebridge[4589]: [4/1/2019, 1:05:26 AM] [TuyaLan] Connected to Test Plug 4
Apr 01 01:05:26 dt2 homebridge[4589]: [4/1/2019, 1:05:26 AM] [TuyaLan] Ready to handle Test Plug 4 with signature {}
Apr 01 01:05:26 dt2 homebridge[4589]: [TuyaAccessory] Socket had a problem and will reconnect to Test Plug 4 (ECONNRESET)
Apr 01 01:05:26 dt2 homebridge[4589]: [TuyaAccessory] Closed connection with Test Plug 4
Apr 01 01:05:26 dt2 homebridge[4589]: [TuyaAccessory] Message from Test Plug 4: {"cmd":10,"data":{"devId":"85074677600194xxxxxx","dps":{"1":t

**Comment by AMoo-Miki** [comment]
@Rantaholic, you mentioned

> After shutting down homebridge, changing state on one plug and starting homebridge
Did you change state with the Tuya app? If so, the Tuya app must be **KILLED** or else it will hold on to its connection with the device and will not allow the plugin to connect.

@lemaygabriel, it would be very helpful if you could share some logs.

**Comment by Rantaholic** [comment]
No, I had killed the Tuya app before the whole process. I changed the state with the physical button. Since using your new version and the intro:false option I’ve had no issues using the plugs.

**Comment by AMoo-Miki** [comment]
@Rantaholic, that is great news.
@lemaygabriel, I would still want to get your problem resolved.

**Comment by AMoo-Miki** [comment]
Closed for inactivity. Please reopen if you still need help.
