### ISSUE TITLE
Device addition

### ISSUE THREAD

**Issue by carsten-h** [AMoo-Miki/homebridge-tuya-lan#31]
a) Teckin Smart Outlet

b) [3/21/2019, 5:34:23 PM] [TuyaLan] Ready to handle Kamera with signature {"1":false,"9":0,"18":0,"19":0,"20":2340,"21":1,"22":649,"23":30787,"24":17570,"25":1185}

c) https://www.amazon.de/TECKIN-Intelligente-fernbedienbar-Stromverbrauch-funktioniert/dp/B07CDCYLQ6

But I have no clue what the dps values other than 20 (Volt) should mean. There is nothing special shown in the Smartlife app for this Outlet.

**Comment by AMoo-Miki** [comment]
If all you want to do is use the device as an outlet, go with `Outlet` as the type; you can switch it on and off through HomeKit.

But if you think there is more to the device and you would rather have them made available to you in the Home app, continue reading :)

To figure out what the `dps` values are:
1) disconnect your phone from the home WiFi
2) configure the device as a `SimpleLight`
3) open your Homebridge logs
4) open the Tuya app and click on different buttons and see what changes you can see showing up in the logs.

Some of those `dp` keys correspond to volts, amps, and power consumption, and coding for them is still ongoing; I will update the instructions as soon as it has been tested. Some others are for timers and automation that HomeKit doesn't even support. If you see any functionality other than these and you were successful in decoding the `dp` for each, reopen the issue with your findings.
