### ISSUE TITLE
Getting only W, not V or A values

### ISSUE THREAD

**Issue by carsten-h** [AMoo-Miki/homebridge-tuya-lan#32]
I have a Smart Outlet from Avatar Controls, that was showing up in the log as this:
[3/21/2019, 9:10:33 PM] [TuyaLan] Ready to handle Kleiner Stecker 2 with signature {"1":true,"2":0,"4":81,"5":33,"6":2345}

So I edited the config into this:
`                {
                    "name": "Kleiner Stecker 2",
                    "type": "Outlet",
                    "manufacturer": "Avatar Controls",
                    "model": "Smart Steckdose",
                    "id": "xxx",
                    "key": "yyy",
                    "voltsId": 6,
                    "ampsId": 4,
                    "wattsId": 5
                },
`

But everything I can see in Eve-App is this:
![Image-1](https://user-images.githubusercontent.com/44360828/54782140-79573900-4c1e-11e9-9287-391ab5e8f877.png)

So only the Watt value is shown, no Volt or Ampere. How is this possible?

In the Smartlife App I can see this:
![Image-1](https://user-images.githubusercontent.com/44360828/54782436-38135900-4c1f-11e9-8b40-eb0ac0fa0241.png)

PS: Is it possible that dps 2 is the KW.h value from Smartlife App?

**Comment by AMoo-Miki** [comment]
That is so odd; even the wattage that it is showing is not correct. Do the logs show any errors? If not, post back and I will add some debug messages to see whats wrong.

regarding the `2` data point, it would be great to see one more log entry and compare that to the figure in the Tuya's app.

**Comment by carsten-h** [comment]
I will create a log when I am back at home at the weekend!
Thanks for your help!

**Comment by AMoo-Miki** [comment]
@carsten-h I have new instructions for getting the device schema that can be found [here](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#adding-support-for-new-devices).

If you still need help with your device, please reopen.
