### ISSUE TITLE
Device Add Request

### ISSUE THREAD

**Issue by tjenvy** [AMoo-Miki/homebridge-tuya-lan#34]
Request to add ability to adjust light kelvin rating.  This light is a tunable white bulb.  I tried the RGB code in there and home bridge crashed with a ton of errors.  It works with simple bulb, but having the tuning of white would be awesome!!!

IOTTON Wi-Fi Smart Bulb LED

Ready to handle bedroom light with signature {"1":false,"2":255,"3":255}

https://smile.amazon.com/gp/product/B07JZ4BVHL/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by tjenvy** [comment]
When using the RGB code for this device,  the output is:


[3/28/2019, 6:08:51 PM] [TuyaLan] Ready to handle bedroom light with signature {"1":false,"2":255,"3":255}
HAP Warning: Characteristic 00000008-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:122
        const [, h, s, b] = value.match(/^.{6}([0-9a-f]{4})([0-9a-f]{2})([0-9a-f]{2})$/i) || [0, 255, 255];
                                  ^

TypeError: Cannot read property 'match' of undefined
    at RGBTWLightAccessory.convertColorFromTuyaToHomeKit (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:122:35)
    at RGBTWLightAccessory._registerCharacteristics (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/RGBTWLightAccessory.js:31:106)
    at TuyaAccessory.BaseAccessory.device.once (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:22:18)
    at Object.onceWrapper (events.js:285:20)
    at TuyaAccessory.emit (events.js:197:13)
    at TuyaAccessory._change (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:240:18)
    at TuyaAccessory._msgHandler (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:176:26)
    at /Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:4096:9
    at Object.process (/Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:2344:17)
    at /Users/tjenvy/.npm-global/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:2252:19

**Comment by AMoo-Miki** [comment]
Your bulb is very different. the `RGBTWLight` will not work for it. I presume `2` and `3` are for brightness and white temperature. It would be great if you could figure which one is which and what they temperature values stand for.

Disconnect your phone from the home WiFi. Define the device as a `SimpleLight` and open the logs. Try changing the brightness in the Tuya app and monitor the logs to see what changes and what the values are; I guess 0 is fully dimmed and 255 is fully lit. Then try changing the white temperature in the Tuya app and see which key changes and what values in the logs correspond to what values in the Tuya app.

If the Tuya app is connected to the home WiFi, it wouldn't allow the plugin to interact with the device and that's why we need to make sure Tuya talks to the device via the cloud.

Best of luck.

**Comment by tjenvy** [comment]
-turn off
[TuyaAccessory] SimpleLight changed: {"1":false,"2":255,"3":255}
-turn on
[TuyaAccessory] SimpleLight changed: {"1":true,"2":255,"3":255}
-brightness 0
[TuyaAccessory] SimpleLight changed: {"1":true,"2":25,"3":255}
-brightness 100
[TuyaAccessory] SimpleLight changed: {"1":true,"2":255,"3":255}
-color warm
[TuyaAccessory] SimpleLight changed: {"1":true,"2":255,"3":0}
-color cool
[TuyaAccessory] SimpleLight changed: {"1":true,"2":255,"3":255}


So your assumption was right.  

1 is on/off
2. is brightness
3. is color temp from 2700-5000K

**Comment by AMoo-Miki** [comment]
Awesome. I will start on it right away.

**Comment by tjenvy** [comment]
Awesome. Thanks for the great work! I appreciate it as do others I’m sure. I’m great at hardware, but wish I was much better at software to do this stuff.

**Comment by AMoo-Miki** [comment]
Change your config to use `TWLight` as the type and you should be good to go. Here is my sample config:
```json
{
  "name": "Bedroom Light",
  "type": "TWLight",
  "manufacturer": "Iotton",
  "model": "Smart Light Bulb",
  "id": "...",
  "key": "..."
}
```
Lemme know if you have any problems, or otherwise.

PS: Software is easy; you just need to find the easiest one to start with. I propose JavaScript over others.

**Comment by tjenvy** [comment]
SWEET, that worked!! Thank you so very much!!

**Comment by nicklayb** [comment]
I used a [Globel tunable white buld](http://www.canac.ca/fr/product/electricite/ampoules/ampoules-del-et-specialites/ampoule-intelligente-del-a19-br-10-w_65215.aspx?unite=001002&sf=pnum%3d8%26ovr%3dtrue%26root%3d857%26categorie%3d1284%252c1285%252c1302%26filterorder%3d0%252c0%252c0%26searchurl%3d%252fafficherbootstrap.aspx%253fsearch%253dglobe%2526searchtype%253d2%2526display%253d5%2526langue%253dfr%2526unite%253d001002%2526sf%253dpnum%25253d8&galst=u%5bSearch%5d) which has a smiliar signature `{"1":false,"3":255,"4":255}`. I impletemented it on my fork by adding `getBrightnessIdentifier` and `getColorTemperatureIdentifier` and extended the TWLight class to override those methods.  I would love to open a PR if you're interested [https://github.com/nicklayb/homebridge-tuya-lan](https://github.com/nicklayb/homebridge-tuya-lan)

**Comment by AMoo-Miki** [comment]
@nicklayb Thanks. PRs are always welcome. I made these field ids configurable in the latest commit.
