### ISSUE TITLE
Smart Outlet not responding.

### ISSUE THREAD

**Issue by Sefaal** [AMoo-Miki/homebridge-tuya-lan#35]
I'm having an issue with an wall outlet that I installed. I connected it to the iphone tuya app and was successful at getting the ID and Key. From that point I added all the required information into my config.json file.

The brand is CE Smart Home - Wifi Smart Outlet 2 Pack.
https://www.costco.ca/CE-Smart-Home-Wi-Fi-Receptacle,-2-pack.product.100475520.html

Here are my logs.

Apr 02 16:19:59 wwhub homebridge[1974]: [2019-4-2 16:19:59] [TuyaLan] Discovered Coffee (40782775600194c1ba37)
Apr 02 16:19:59 wwhub homebridge[1974]: [2019-4-2 16:19:59] [TuyaLan] Connected to Coffee
Apr 02 16:19:59 wwhub homebridge[1974]: [2019-4-2 16:19:59] [TuyaLan] Ready to handle Coffee with signature {"101":false,"102":0}

now i'm a little confused as to why it is using 101 and 102. only the bottom receptacle is controlled and the top one is a dumb always on receptacle.

here are the logs when I toggle it on and off from Home app.

Apr 02 11:58:21 wwhub homebridge[1974]: [TuyaAccessory] Sending Coffee {"1":true}
Apr 02 11:59:49 wwhub homebridge[1974]: [TuyaAccessory] Sending Coffee {"1":true}
Apr 02 11:59:51 wwhub homebridge[1974]: [TuyaAccessory] Sending Coffee {"1":false}
Apr 02 11:59:53 wwhub homebridge[1974]: [TuyaAccessory] Sending Coffee {"1":true}

Let me know if I can get this going.

Thank you.

**Comment by AMoo-Miki** [comment]
`101` is certainly not what I have seen around. Let's try something.

1) update the plugin to the latest unreleased code with `npm i -g AMoo-Miki/homebridge-tuya-lan`
2) change the device type to `CustomMultiOutlet` and match this:
```json
{
  "name": "Coffee",
  "type": "CustomMultiOutlet",
  "manufacturer": "CE Smart",
  "model": "LQ-2-W3",
  "id": "xxxxxxx",
  "key": "xxxxxxxx",
  "outlets": [
    {
      "name": "Bottom",
      "dp": 101
    }
  ]
}
```
3) restart Homebridge.

Lemme know how this works.

**Comment by bugs181** [comment]
Before posting a new issue, thought I'd comment my discoveries here. I'm receiving a very similar message. What I've found is that if trigger the device on/off in one of the apps (CE Smart or Smart Life), then it will start to work with Homebridge. The status get's updated immediately and you can use the switch.

Here's my output:
```
[2019-7-13 17:09:19] [TuyaLan] Ready to handle Bedside Fan with signature {"1":false,"11":0}
[2019-7-13 17:09:21] [TuyaLan] Ready to handle Milo with signature {"1":false,"11":0}
[TuyaAccessory] Sending Milo {"1":false}
[TuyaAccessory] Sending Milo {"1":true}
```

**Comment by AMoo-Miki** [comment]
@bugs181, the original poster had a device that didn't use the standard(?) power datapoint identifier. However, reading your message, it sounds like your device doesn't work right off the bat. If that is the case please create a new issue so we can work together and find a solution.
