### ISSUE TITLE
What command to run?

### ISSUE THREAD

**Issue by samsonrosen** [AMoo-Miki/homebridge-tuya-lan#36]
Hi! I’m trying to get my ID and Key. I have completed step:

npm i -g anyproxy @tuyapi/cli.

But then the instructions say:

Execute anyproxy-ca

I’m not sure what I should be doing to run this. I am using Mac OS.

Thanks in advance.

**Comment by uberfunk** [comment]
> Execute anyproxy-ca

Just type **anyproxy-ca** and hit enter.
I followed [these instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) last year to get the ID and Key (before codetheweb deprecated his version of homebridge-tuya), it's basically the same as the instructions AMoo-Miki wrote up.

**Comment by AMoo-Miki** [comment]
@samsonrosen, were you able to solve your problem?

**Comment by AMoo-Miki** [comment]
Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.
