### ISSUE TITLE
Smart Dimmer not dimming

### ISSUE THREAD

**Issue by uberfunk** [AMoo-Miki/homebridge-tuya-lan#37]
A continuation of [this Smart Dimmer issue](https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/19)...

I have a CE Smart dimmer switch, [purchased from Costco](https://www.costco.ca/CE-Smart-Home-Wi-Fi-Smart-Dimmer-Light-Switch%2c-2-pack.product.100417574.html), and the dimming worked with [codetheweb's homebridge-tuya](https://github.com/codetheweb/homebridge-tuya). Mine is also show 1 and 2 in the logs, not 1 and 3. What other details would you need to make this work? Thanks!

[4/12/2019, 9:10:56 PM] [TuyaLan] Ready to handle Master Ceiling Light with signature {"1":true,"3":50}
[4/12/2019, 9:10:56 PM] [TuyaLan] Discovered Kitchen Island Light (XXXXXX)
[4/12/2019, 9:10:56 PM] [TuyaLan] Connected to Kitchen Island Light
[4/12/2019, 9:10:56 PM] [TuyaLan] Ready to handle Kitchen Island Light with signature {"1":false,"3":255}
[TuyaAccessory] Sending Kitchen Island Light {"2":255}
[TuyaAccessory] Sending Kitchen Island Light {"1":true}
[TuyaAccessory] Sending Kitchen Island Light {"2":200}
[TuyaAccessory] Sending Kitchen Island Light {"1":true}
[TuyaAccessory] Sending Kitchen Island Light {"2":149}
[TuyaAccessory] Sending Kitchen Island Light {"1":true}
[TuyaAccessory] Sending Kitchen Island Light {"2":128}
[TuyaAccessory] Sending Kitchen Island Light {"1":true}
[TuyaAccessory] Sending Kitchen Island Light {"2":121}

**Comment by AMoo-Miki** [comment]
@uberfunk, I presume your config already has `"type": "SimpleDimmer"`. Add a new parameter below that as `"dp": 3,` and you should be good to go.

Lemme know if you have a problem or otherwise.

**Comment by uberfunk** [comment]
Thank you! Updated the package, added `"dp": "3"` to each smart dimmer, and it worked. Thank you for your work!

**Comment by AMoo-Miki** [comment]
@uberfunk I am glad it works as you want.
