### ISSUE TITLE
Add new device (relay, discovery problem)

### ISSUE THREAD

**Issue by jakobsudau** [AMoo-Miki/homebridge-tuya-lan#38]
Hello,
Thanks for this great plugin, works really well!
I have bought some eMylo relays ([YSC116D3N-FBM](https://www.amazon.de/gp/product/B07FP8N7DS/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1)) which I would like to use with this plugin.

When I config one test relay as a `SimpleLight` it doesn't show up in the logs though, it says: 
`Failed to discover my_custom_relayName (my_custom_virtualID) in time but will keep looking.` Confirmed twice that the Virtual ID and Key are correct, device is online and reachable via Tuya App.

Any ideas how I can make it reachable? Also tried as `Outlet`, then Homebridge fails to start.

This device has some extra functionality compared to a simple `Outlet` in the Tuya app - you can set a timer and countdown (not so important imo) and it has settings to remember the last status after being disconnected from power ("online", "offline", "same status as before" - this is quite important imo).

**Comment by AMoo-Miki** [comment]
@jakobsudau, I am gad it is working to your liking. While you have the device in `SimpleLight`, add `"ip": "<DEVICE-IP>"`, putting the device's IP there. This should make the plugin connect to the device, despite not being able to discover it.

If you haven't already, update to the latest unreleased version of the plugin by running `npm i -g AMoo-Miki/homebridge-tuya-lan`.

Also, HomeKit currently doesn't support any of the extras you mentioned and your device would eventually be an `Outlet`. Let's get your device found and then we will look into why the outlet setting acted up on you.

Good luck.
