### ISSUE TITLE
Convector with problems (or adding a new device)

### ISSUE THREAD

**Issue by fparrav** [AMoo-Miki/homebridge-tuya-lan#39]
I have problems with a convector Betterlife brand, when configured as a convector, it works without problems when changing the temperature, but something happens with the ignition button that does not respond. When changing the temperature (previously turned on in the convector app [Smartlife or Tuyasmart] after a few seconds it turns off, even leaving the fan speed to the maximum.) I do not notice that the fan speed modifies parameters of LOW or High.

The [link of the convector panel ](https://www.betterlife.cl/product/panel-electrico-con-wi-fi-cg-10led/)

Image of the app: 
![IMG_2317](https://user-images.githubusercontent.com/9319430/56535971-ecf4aa80-652a-11e9-89f6-f38fed051d8b.PNG)

Signature
` Ready to handle Calefactor Dormitorio with signature {"1":false,"2":19,"3":16,"4":"low","12":0}
`

**Comment by AMoo-Miki** [comment]
@fparrav, can you please post your config too.

Also, I see that your signature is missing dp of "7" and has a few extra ones, "1" and "12". This must be why things are not working the way they should. I have a feeling "1" does what "7" does so let's try something:

- Update your plugin to the latest version with `npm i -g AMoo-Miki/homebridge-tuya-lan`
- In the config block of your device, add `"dpActive": 1,` (don't forget the comma at the end)
- Restart Homebridge.
- Check if you can turn it on and off.

Lemme know how things go.

**Comment by fparrav** [comment]
Thank you very much for the response, it is already working almost perfect. 



 `{
            "platform": "TuyaLan",

            "devices": [
            {   "dpActive": 1,
                "name": "Calefactor Dormitorio",
                "type": "Convector",
                "manufacturer": "Betterlife",
                "model": "CG-10LED",
                "id": "05200674dc4f222ac1c1",
                "key": "4bac481723a6c641",
                "cmdLow": "Low",
                "cmdHigh": "High",
                "minTemperature": 5,
                "maxTemperature": 50,
                "noChildLock": true


            }
        ]
        }`

**Comment by AMoo-Miki** [comment]
@fparrav, looking at the log you posted in your first message, the device expects "low" in all lower case; it most probably wants "high" in lower case too. Change `cmdLow` to "low" and `cmdHigh` to "high" and see if that gets the fan to work.

regarding the AF mode, can you tell me a bit more? what is it and what it does? knowing that I can look up HomeKit specs to see if it can be mapped to anything in particular.

**Comment by fparrav** [comment]
@AMoo-Miki  Thanks for the reply, the plugin has worked perfectly all this time, and now I did what you told me and change cmdLow to "low" and cmdHigh to "high" and it works! there is only a small detail that, being a slider, my convector sounds while I slide my finger confirming each position (it does not sound slowly) at the moment I created an atmosphere with the setting low and another high and sent the instruction in a single command.


Regarding the AF mode, it corresponds to "antifreeze" when activating the temperature controls are deactivated and enters an automatic mode of operation if the temperature is below 5 degrees Celcius to prevent freezing.

But the most important thing is that it is working at 99% and that's great, thanks!

**Comment by AMoo-Miki** [comment]
Thanks for clarifying and I am glad things are working.

Sadly I can't find anything in HomeKit that matches AF. I will remember to look out for anything new that we might be able to use.

Regarding the sound, since I don't have this device, I am not sure what you were referring to. Does it make the sound when you change the temperature? If yes, that is super simple for me to handle; let me know :)

**Comment by AMoo-Miki** [comment]
I just pushed some changes that should eliminate the repeated setting. See if that helps the sound.
Update your plugin to the latest version with `npm i -g AMoo-Miki/homebridge-tuya-lan`.

Good luck (to us both)

**Comment by fparrav** [comment]
sorry for my poor English, regarding the sound is a confirmation beep that sounds every time I send a command or slide a control, unfortunately in my convector it sounds very strong, but with the scenes or settings I send the whole configuration in a single “beep  "

**Comment by AMoo-Miki** [comment]
@fparrav you English is fine :) Were you able to update the plugin and check if it is better?

Try `npm i -g homebridge-tuya-lan@rc` to get the latest `rc` release or `npm i -g homebridge-tuya-lan` for the latest `stable` release.

**Comment by fparrav** [comment]
Sorry for the delay, holiday season in my country. I did the tests and noticed that the `stable` version responds much better, in the `rc` repeated commands are sent as I see in the log ... for example when switching on the command is sent 3 times (with their respective 3 response beeps)

**Comment by AMoo-Miki** [comment]
That is odd. I will check to see what causes it to send 3 commands.

**Comment by fparrav** [comment]
The 3 commands occur sometimes (maybe it's api problems).  Sometimes it also happens that if you turn off the convector while it is in a "low" state, when you turn on it sends the power command and sends the "high" command.  But not always happening I have no evidence of under what conditions it occurs.

**Comment by AMoo-Miki** [comment]
This must be the Home app's logic and I don't believe I can override it. Lemme know if I can help in any other way.
