### ISSUE TITLE
Homebridge discovering device then crashing while trying to add

### ISSUE THREAD

**Issue by TheHomekitWayFinder** [AMoo-Miki/homebridge-tuya-lan#47]
I own a Kogan SmarterHome Air Conditioner that can both heat and cool. I have trued adding it to HomeKit through this plugin but then when it discovers the device my local area network it proceeds to crash homebridge. Here is the link to the air conditioner: https://www.kogan.com/au/buy/kogan-smarterhome-41kw-portable-air-conditioner-14000-btu-reverse-cycle/?openModal=2

Here is the log from homebridge:

`[5/12/2019, 8:32:13 PM] [TuyaLan] Discovered AC (71645600b4e62d215921)
C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\node_modules\node-forge\lib\aes.js:203
var len = tmp.length();
^

TypeError: tmp.length is not a function
at forge.aes.Algorithm.initialize (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\node_modules\node-forge\lib\aes.js:203:19)
at new forge.cipher.BlockCipher (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\node_modules\node-forge\lib\cipher.js:118:18)
at Object.forge.cipher.createCipher (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\node_modules\node-forge\lib\cipher.js:42:10)
at new TuyaAccessory (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\lib\TuyaAccessory.js:28:36)
at EventEmitter.TuyaAccessory.discover.on.config (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\index.js:77:32)
at EventEmitter.emit (events.js:182:13)
at Socket.server.on.msg (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\homebridge-tuya-lan\lib\TuyaAccessory.js:343:24)
at Socket.emit (events.js:182:13)
at UDP.onMessage [as onmessage] (dgram.js:628:8)`

here is my config.json file:

`{
"bridge": {
"name": "Homebridge",
"username": "xx:xx:xx:xx:xx",
"port": 51826,
"pin": "xxx-xx-xxx"
},

"description": "This is an example configuration file.",

"platforms": [{
		"platform": "TplinkSmarthome",
		"name": "TplinkSmarthome"
	},
	{
		"platform": "TuyaLan",
		"devices": [{
			
			"name": "AC",
			"type": "AirConditioner",
			"manufacturer": "Kogan",
			"model": "SmarterHome Air Conditioner",
			"id": "71645600b4e62d215921",
			"key": "--------key---------"
		}
		]
	}
],

"accessories": [{
	"accessory": "Xbox",
	"name": "Xbox",
	"ipAddress": "xx.x.x.x",
	"liveId": "xxxxxxxxxxxx"
}]
}`

**Comment by TheHomekitWayFinder** [comment]
#2

**Comment by TheHomekitWayFinder** [comment]
@AMoo-Miki can you have a look into this and try and see why it’s not working

**Comment by AMoo-Miki** [comment]
I looked at `node-forge` code and it looks like it is not liking your key.
1) Update your plugin to the latest version with `npm i -g AMoo-Miki/homebridge-tuya-lan` as I have updated the plugin's dependencies to use a newer version of `node-forge`.
2) Count the number of characters in your key; the valid lengths are 16, 24, and 32. If yours is none, please go through the process of obtaining the id and key again.

Lemme know how it goes.

**Comment by AMoo-Miki** [comment]
Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.

**Comment by TheHomekitWayFinder** [comment]
Ok, thanks. I will have a look at this know.

**Comment by TheHomekitWayFinder** [comment]
Just a quick update. I have just used the command that you provided and it has discovered the device however homebridge crashes not long after discovering the device and is giving an Key Error saying that my key is too long. I will try and get and updated key and id now and report back.

**Comment by AMoo-Miki** [comment]
@TheHomekitWayFinder, regarding Tuya and Homekit, that is what they told me. Let's hope it is not limited to Siri Shortcuts. Their implementation would save us from all these hoops.

**Comment by TheHomekitWayFinder** [comment]
When I try to get the key for my air conditioner, tuya-lan-find starts to print out somethings and then crashes

**Comment by TheHomekitWayFinder** [comment]
![IMG_0E042A964B80-1](https://user-images.githubusercontent.com/46802814/64470384-ea5ebe80-d174-11e9-889e-f1344d91f005.jpeg)

**Comment by AMoo-Miki** [comment]
If it shows garbage, it is an indicator of a bad certificate. [Delete ](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions#cleanup-instruction) any previous NodeMITMProxyCA certificates you might have on the phone before you start `tuya-lan-find`. I haven't had anyone else report using `tuya-lan-find` yet but I am sure there would be edge cases that need handling.

Regarding Homebridge crashing, can you get your hands on some logs to see what's causing it?

**Comment by AMoo-Miki** [comment]
I ran it on Windows and it didn't give me any trouble. It shows many "socket hang up" errors but those can be ignored. I will suppress them soon.

**Comment by TheHomekitWayFinder** [comment]
Unfortunately, it never seems to produce any log files and all I have is a picture
 of it crashing and saying that it has an invalid key length. I will try and run tuya-lan-find again after deleting the certificates again.

Here is the photo of the error:

![IMG_1626](https://user-images.githubusercontent.com/46802814/64470529-209d3d80-d177-11e9-8c3c-c19e1c3c854f.PNG)

**Comment by AMoo-Miki** [comment]
Is it possible that you are adding the key and id inverted?

**Comment by TheHomekitWayFinder** [comment]
No, as in the app id now shows the Virtual ID and i have compared the two and they are both the same so im presuming it's just that the key is wrong.

**Comment by AMoo-Miki** [comment]
Can you please update with `npm i -g homebridge-tuya-lan@rc` and give it shot?

**Comment by TheHomekitWayFinder** [comment]
I have just run tuya-lan-find again and it gives lots of socket hang up errors but it doesnt give the id or key of my air conditioner. I have also just today purchased a Arlec 4 outlet power strip and that uses the tuya protocol and therefore i need to get this working so that i can add that to homekit.

I will run the update and give it another shot in a sec.

**Comment by TheHomekitWayFinder** [comment]
The update still isnt working. Unfortunately

**Comment by AMoo-Miki** [comment]
it crashed? How long is your key?

**Comment by TheHomekitWayFinder** [comment]
yep it crashed again. in my config file my key is 16 characters long however it was 17 before so I believe that my key may be wrong. 

Version of 
tuya-lan-find is 1.5.0-rc.4
node is 10.15.0
homebridge is 0.4.50

**Comment by AMoo-Miki** [comment]
```
netsh advfirewall firewall add rule name="MITM Proxy" dir=in action=allow protocol=TCP localport=8080
```

**Comment by TheHomekitWayFinder** [comment]
im still getting the socket hang up errors and nothing else so i dont know whats happening. I used that command to change the firewall but its still giving me the same result

![Image 2](https://user-images.githubusercontent.com/46802814/64471061-f5b6e780-d17e-11e9-85c1-fe40dbacb890.jpeg)

**Comment by AMoo-Miki** [comment]
While these socket timeouts are shown, can you please kill the Tuya app on your phone and open it again? Please make sure you kill it and not just minimize it.

PS, I just pushed v1.5.0-rc.5 to NPM to suppress the `socket hang up` messages.

**Comment by TheHomekitWayFinder** [comment]
No, i am using the kogan smarterhome app. i am making sure that i kill the app by double clicking the home button and swiping up on the app

**Comment by AMoo-Miki** [comment]
This will only work with the Tuya Smart app to fetch the `id` and `key`.

**Comment by TheHomekitWayFinder** [comment]
ok i will try that now

**Comment by AMoo-Miki** [comment]
Oops, and I guess if you add it to Kogan, you will have to reset it again which most probably changes the id and key.

**Comment by TheHomekitWayFinder** [comment]
there are 2 instances of the tuya.m.my.group.device.list do i change both of them

**Comment by AMoo-Miki** [comment]
yes please.

**Comment by TheHomekitWayFinder** [comment]
it still isnt pulling the key and id

**Comment by AMoo-Miki** [comment]
I see, give me a second. Lemme cook up something.

**Comment by TheHomekitWayFinder** [comment]
yes it did, all of the same socket hang up errors.

**Comment by AMoo-Miki** [comment]
Download this file, unzip, and place `kogan.js` next to the `cli.js` file. To run it, open `cmd` in this folder and type `node kogan.js`.
[kogan.zip](https://github.com/AMoo-Miki/homebridge-tuya-lan/files/3586394/kogan.zip)

**Comment by TheHomekitWayFinder** [comment]
it doesnt have any of the socket hang up errors like before but it does have a connect ENOBUFS and connect EADDRINUSE but its still not giving me the key and id of the air conditioner

**Comment by AMoo-Miki** [comment]
Where was EADDRINUSE ?

**Comment by TheHomekitWayFinder** [comment]
![Image 3](https://user-images.githubusercontent.com/46802814/64472119-01f57180-d18c-11e9-9bd0-71f81e8eeee6.jpeg)

**Comment by AMoo-Miki** [comment]
Can you delete the cert from your phone and scan the QR code from the Kogan.js script?

**Comment by TheHomekitWayFinder** [comment]
I deleted the certificate from the cli.js script before I scanned the QR code from the Kogan.js script. But I can’t do anything at the moment as I have just gone out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
I understand. I will think a bit to see what we can do about this and post back.

**Comment by TheHomekitWayFinder** [comment]
Do you want me to see if I can source the signature some how?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
The `key` and `signature`, yeah.

**Comment by TheHomekitWayFinder** [comment]
What about MITMproxy that has a web interface like anyproxy did

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
You mean [this](https://mitmproxy.org/)? I just tested it on Windows and it is great.

After you install it, change the proxy settings on your phone to your Windows IP and 8080. Then open `mitm.it` on your phone to install the certificate; the process is identical to this plugins.

**Comment by TheHomekitWayFinder** [comment]
I have just tried to reset the device and add it to the TuyaSmart app, however the device keeps timing out before the app has finished pairing. But when I go back into the Kogan SmarterHome app it pairs very quickly

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
I just tried using Mitmproxy after adding the air conditioner back to the Kogan SmarterHome app and it would pull up any details to do with it. It pulls up lots for websites but nothing for apps. The same happens when I try to get the id and key of my Arlec Grid Connect Power Strip.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
Do u have a Mac?

**Comment by TheHomekitWayFinder** [comment]
Yes I do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
I guessing this is out of date but, https://gist.github.com/aceslick911/0cac96ab122fa9c6cd9ca18a696ea961

**Comment by AMoo-Miki** [comment]
Thanks. Sadly it didn't provide much help. Lemme copy-paste what I wrote someone else for you

**Comment by TheHomekitWayFinder** [comment]
Ok will try that in a bit. Is there anyway of maybe asking if Tuya could present the local key in the app when connected to the same network as the devices as it would make it much easier for external integrations such as homebridge. The only thing would be security.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
Here is the signature that I acquired from command prompt when running homebridge with the old key and that isn’t working. It shows up but then when controlling through HomeKit the device doesn’t respond to the commands but still appears online. I guessing this is because it has the wrong key.
`Ready to handle AC (AirConditoner:3.1) with signature {“1”:false, “2”:24, “3”:17, “4”:“HEAT”, “5”:“1”, “19”:”C”, “102”:false, “103”:0, “104”:false, “105”:0, “106”:0, “110”:0}`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
The `3.1` devices don't use encryption while fetching the signature.

One way to check if the `key` is really bad is to watch the logs and trigger a change on the device using the controls on it, maybe just turn it on or off, or change the temperature. If you see an error about `Odd message ... with command 8` it means the `key` is bad. If no error is shown, it is _probably_ good.

**Comment by TheHomekitWayFinder** [comment]
I just tried the pcap method but it was giving errors I don’t know whether I was doing it wrong orwhat

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
Do you know what error it gave you? Also can you check if the `key` is really good using my previous message?

**Comment by TheHomekitWayFinder** [comment]
Also did you mean the UDID or the ECID

**Comment by TheHomekitWayFinder** [comment]
@AMoo-Miki i have just sent through the 2 files that you requested from wireshark through to your email. I dont know my correct key so therefore i didnt provide it. If there is anything else you need just let me know. I hope that you are able to distinguish a key from that.

**Comment by TheHomekitWayFinder** [comment]
I just ran thing that you asked me to do previously to check the key and it kept coming back with odd message from AC with command 8

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
There wasn’t any error it was just that I was using the wrong device number. I was using the ECID rather than the UDID therefore it wasn’t working.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AMoo-Miki** [comment]
> 
> 
> Also did you mean the UDID or the ECID

Silly me. I fixed the instructions. Thanks for pointing it out.

**Comment by TheHomekitWayFinder** [comment]
@AMoo-Miki sorry I have been so busy recently and when I have time I will try it and let you know

**Comment by AMoo-Miki** [comment]
Of course. Ping me whenever you get a chance.

**Comment by TheHomekitWayFinder** [comment]
@AMoo-Miki I have just gotten round to trying some stuff out, and I bought a new powerboard the other week and i wanted to try and get that into home bridge so when I got it I loaded it into the tuya smart app and have just today been able to successfully retrieve the key from the device after following the instructions I realised that when I had been previously attempting to retrieve the key I hadn't been granting the certificate full trust settings, I have also been able to load the air conditioner into homebridge fully and I am now able to control it through HomeKit. However, do you know whether there is any way to separate the outlets on the powerboard as I am using the board in many different rooms however HomeKit won't allow me to separate them based on places and add each outlet to favourites instead of just the master board.

**Comment by AMoo-Miki** [comment]
@TheHomekitWayFinder that is good to know.

I too found the grouping annoying and good news is that with the latest iOS, they have an option to separate the icons. I just saw it in my 13.3.1; give it a shot.

Lemme know if I can help in any other way.
