### ISSUE TITLE
Found device on tuya-cli list-app but homebridge failed to discover 3 gangs switch

### ISSUE THREAD

**Issue by haepiyang** [AMoo-Miki/homebridge-tuya-lan#48]
As the title said, I had used tuya-cli to get the id and key of my devices then add the config.
My previous tuya smart breaker work well without any problem and it's still working now.
I've just bought a 3 gangs wall switch form Aliexpress and do the samething but homebridge can not discover it. I've tried SimpleLight, MultiOutlet or CustomMultiOutlet and neither of them work.

Link to device: https://aliexpress.com/item/Tuya-Smart-home-WiFi-Touch-Schalter-Drahtlose-Wand-Touch-Telefon-APP-control-UNS-typ-1-2/32980592592.html

**Comment by AMoo-Miki** [comment]
Can you please define it as a SimpleLight and post some logs?

**Comment by haepiyang** [comment]
Yeah I've updated to rc and it's working now. Thank you very much!

**Comment by AMoo-Miki** [comment]
That is great news. Best of luck.
