### ISSUE TITLE
Multiple instances of the same accessory

### ISSUE THREAD

**Issue by socalcal** [AMoo-Miki/homebridge-tuya-lan#49]
I'm seeing multiple instances of the same accessory, but only one of the actual listings in HomeKit does anything.  In other words, I have one smart outlet, but there are three showing in homebridge, but only one of them actually does anything.  Any ideas?  Thanks!

**Comment by TheHomekitWayFinder** [comment]
Have you tried deleting the cached accessories file in you homebridge fuel and then restarting homebridge to see if that makes a difference

**Comment by socalcal** [comment]
Would that be the same as quitting homebridge and removing the persist folder? If so, yes, multiple times as I’m always adding/modding accessories. That’s the only way to add new accessories through homebridge, no?

**Comment by TheHomekitWayFinder** [comment]
No there should be a file called cachedaccessories in the accessories folder of the .homebridge file. Just shut down homebridge then delete that file and restart homebridge

**Comment by socalcal** [comment]
That worked!  Thanks!

**Comment by TheHomekitWayFinder** [comment]
No problems I’m glad I could be of help to you
