### ISSUE TITLE
LARKKEY Outdoor Smart Outlet Plug with 2 Sockets

### ISSUE THREAD

**Issue by socalcal** [AMoo-Miki/homebridge-tuya-lan#50]
Product link:

https://www.amazon.com/gp/product/B07LGS6BS3/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

I initially set this up as a MultiOutlet with the following in config.json:

{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Patio",
                    "type": "MultiOutlet",
                    "manufacturer": "LARKKEY",
                    "model": "Outdoor Smart Outlet",
                    "id": "mydeviceid",
                    "key": "mydevicekey,
                    "outletCount": 2,
                    "ip": "mydeviceip"
                }

Upon starting homebridge, I got:

[TuyaLan] Failed to discover Patio (mydeviceid) in time but will connect via mydeviceip.
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Closed connection with Patio
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)

I changed config.json to SimpleLight and got this:

[TuyaLan] Failed to discover Patio (mydeviceid) in time but will connect via mydeviceip.
[TuyaLan] Patio has a different type (7 vs 5)
[TuyaLan] Unregistering Patio
[TuyaLan] Connected to Patio
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Closed connection with Patio
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Closed connection with Patio

Hope this helps?  Any ideas?  Thanks!

**Comment by socalcal** [comment]
I guess this repository is no longer supported?  Is there a new tuya homebridge repository that's active?

**Comment by AMoo-Miki** [comment]
Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.

**Comment by socalcal** [comment]
Thanks for the response.  I installed the rc release and am now getting this:

[9/7/2019, 12:52:03 PM] [TuyaLan] Patio - identify
[9/7/2019, 12:52:05 PM] [TuyaLan] Patio - identify
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Sending first query to Patio (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)
[TuyaAccessory] Sending first query to Patio (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Patio (Error: ERR_PING_TIMED_OUT)

My config.json has this device entry:

                    "name": "Patio",
                    "type": "MultiOutlet",
                    "manufacturer": "LARKKEY",
                    "model": "Outdoor Smart Outlet",
                    "id": "0008XXXXdc4f22f3XXXX",
                    "key": "7d9XXXX5206bXXXX",
                    "outletCount": 2,
                    "ip": "10.0.1.125"

**Comment by AMoo-Miki** [comment]
If you have the latest `rc`, please add `"pingTimeout": 3600` to your config to see if we can get rid of the ping timeouts. The `rc` has been changing frequently. Please get rid of the `ip` from your config while you are at it.

After you restart homebridge:
1. Look for anything just after `Sending first query to Patio (3.3)`
1. Does the Home app show them with an exclamation mark, indicating they are unresponsive?
1. Using the button on the device, turn it on or off. Do you see any messages in the log?

**Comment by socalcal** [comment]
Looks like manually switching it registered it.  Appears to be working now.  Thanks so much for your help!

I'm still getting this intermittently, but it registers on HomeKit and responds when switching on/off:

[TuyaAccessory] Socket had a problem and will reconnect to Patio (ECONNRESET)
[TuyaAccessory] Sending first query to Patio (3.3)

**Comment by socalcal** [comment]
1. This is what I see after:
[TuyaAccessory] Socket had a problem and will reconnect to Patio (ECONNRESET)

2. Yes, but somehow I got them to actually register, but turning on/off does nothing.  I'm not sure how I got the exclamation points to go away.

3. No messages when turning on/off at device.

I did, however run the tuya app while homebridge was running and the sockets register the correct status when turning on/off with the tuya app.  Using Home app does nothing other than change the status while not affecting the outlet at all.

**Comment by AMoo-Miki** [comment]
Can you post 15-20 lines of sequential logs? If you are on macOS or linux, use `tail` and `| grep Tuya`. The sequence of messages (preferably with timestamps) will let me draw an accurate picture of this; what I need to see would start with `Discovered` and at least 45 seconds after it.

Also, from our conversation, I haven't seen anything to give me confidence that we have the correct `key`. Are you using the key from May or did you get a chance to get the `key` with the new instructions?

**Comment by socalcal** [comment]
Here's what I get with tail:

[9/7/2019, 3:50:23 PM] [TuyaLan] Discovered Patio (00087488dc4f22f3403d) identified as MultiOutlet (3.3)
[9/7/2019, 3:50:23 PM] [TuyaLan] Connected to Patio
[TuyaAccessory] Sending first query to Patio (3.3)
[TuyaAccessory] Socket had a problem and will reconnect to Patio (ECONNRESET)
[TuyaAccessory] Sending first query to Patio (3.3)

I used the new instructions and got the same key I was using before.

**Comment by AMoo-Miki** [comment]
I couldn't find the 2-outlet one on Amazon to buy and check. Did you buy it from Amazon yourself?

**Comment by socalcal** [comment]
Yes, and the link I provided in the original post is the same that's shown in my order history.  Apparently links to a different product now.

**Comment by AMoo-Miki** [comment]
If you don't have a Mac, or don't think you can help with some debugging, I will go ahead an order one. Lemme know please.

**Comment by socalcal** [comment]
I have a Mac and am willing to help debug, but I only have rudimentary terminal knowledge. You’ll have to be patient and give super simple instructions that I’ll be able to follow.

**Comment by AMoo-Miki** [comment]
Hehehehe. Of course.

**Comment by AMoo-Miki** [comment]
@socalcal, before you do the sniffing, please update to the latest `rc` using `npm i -g homebridge-tuya-lan@rc`. Someone sent me their packet logs which resulted in changes that fixed their similar problem; it might solve yours too.

**Comment by socalcal** [comment]
I totally missed the message with the instructions in it, but I just installed the rc and it works!  Thanks so much!

**Comment by AMoo-Miki** [comment]
That's great news. Best of luck.

**Comment by HELLBENDER28** [comment]
@socalcal I have 2 LED Larkkey lights that I want to get into Homebridge. Would you be interested in getting this working also?

**Comment by socalcal** [comment]
I don't have a need, but if you're looking for assistance, you should probably send a message to AMoo-Miki or open a new issue.
