### ISSUE TITLE
[New Device] RGBTW + Plug

### ISSUE THREAD

**Issue by drforno** [AMoo-Miki/homebridge-tuya-lan#55]
SA01 Smart Power Socket Wifi Wireless

Signature:
Ready to handle Lampada stelo with signature {"1":true,"2":"white","3":60,"4":255,"5":"1900000000ff19","6":"00ff0000000000","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000","101":true}

https://www.jumia.co.ke/generic-sa01-smart-wifi-control-socket-wireless-plug-support-voice-control-power-count-remote-control-switch-for-smartphones-compatible-with-alexa-google-home-17174455.html

This is the closed to mine.

It's a smart plug with an RGB led dimmerable and a USB port. The plug and the led are individually controllable.

First time i've configured as SimpleLight, but i can control only RGB led, not the plug. Then i tried to configured as Outlet. Sometime i was able to turn on the plug, but not to turn it off again.

I've tried also MultiOutlet with outletCount = 2, with the same problem.

Thankyou

**Comment by AMoo-Miki** [comment]
Sorry for getting back to you so late. It feels like `1` controls the RGBTW LED part and `101` the plug. I will have this ready for you before my day ends (in 20 hours).

**Comment by AMoo-Miki** [comment]
Please update to the latest `rc` release by doing `npm i -g homebridge-tuya-lan@rc` and follow the [Supported Devices](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#outlets-with-white-and-color-lights) instruction to set your `RGBTWOutlet` up.

Let me know how this goes.

**Comment by drforno** [comment]
I've installed the `RC` and now it works great.

Thank you

**Comment by AMoo-Miki** [comment]
That's great news. My pleasure.
