### ISSUE TITLE
Please Support Smart Thermostat by Tuya

### ISSUE THREAD

**Issue by arnoutzw** [AMoo-Miki/homebridge-tuya-lan#57]
Ready to handle Smart Thermostat with signature {"1":true,"2":34,"3":46,"4":"1","5":false,"6":false,"102":0,"104":true}

Encoding:
{ON/OFF,Set Temp x2,Meas Temp x2, dunno , dunno , dunno, ..}

**Comment by arnoutzw** [comment]
Sold here : https://nl.aliexpress.com/item/MJZM-BGL-002-WiFi-Hand-Thermostaat-Temperatuur-Controller-voor-Gas-Boiler-Alexa-Google-Home-Thermoregulator-voor/32906986712.html?spm=a2g0s.9042311.0.0.27424c4dJhEFCf

**Comment by AMoo-Miki** [comment]
Please install the latest `rc` release by doing `npm i -g homebridge-tuya-lan@rc`. From your signature, [SimpleHeater](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#simple-heaters) should work just fine.

I have updated the instructions for new devices; having the "schema" will help figure out what the other data-points are.

Bets of luck.

**Comment by arnoutzw** [comment]
Hi AMoo-Miki, 

Thank you! It seems to connect fine indeed with SimpleHeater configuration. 

However for some reason I can only use it in Read-only mode. Any change I make in the Home app does not show on the thermostat. I see the command being sent in the log.

Do you have any idea what the cause might be?

**Comment by arnoutzw** [comment]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/49884192/64472335-f9d20d80-d15c-11e9-986b-6cda4a3a6072.png">
Mmm for some reason Homebridge server crashes when I change setpoints with official App.

**Comment by arnoutzw** [comment]
Nvm , key was no longer up to date ;) everything working perfectly now!

**Comment by AMoo-Miki** [comment]
That is wonderful news.
