### ISSUE TITLE
SimpleDimmer not accepted?

### ISSUE THREAD

**Issue by jd0394** [AMoo-Miki/homebridge-tuya-lan#64]
Finally got my bulbs back onto homebridge - had to use Charles proxy to find the keys instead of tuna-cli and anyproxy. 

But now the type SimpleDimmer is not an accepted type. How do I fix this? Should it be called something else?

**Comment by Rantaholic** [comment]
Try this solution from a previously closed issue for the same question and possibly #37 at the bottom of that thread.

https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/19#issuecomment-472334773

**Comment by jd0394** [comment]
Sorry this is so late. But adding "dp":3, did not fix it. It still says "no valid configured devices found" and "___ doesn't have a valid type defined" when I have SImpleDimmer in the config.json

**Comment by Rantaholic** [comment]
Did you do what was suggested in issue #19?
(Just updating to the latest version will NOT work you have to run the exact command below to install this specific version, possibly with sudo if you get errors installing without it)

npm i -g AMoo-Miki/homebridge-tuya-lan

**Comment by jd0394** [comment]
Sorry, I missed #19 last time I looked. Tried that and it fixed it, thanks!

**Comment by AMoo-Miki** [comment]
The SimpleDimmer is not in the released version of the plugin. The latest `SimpleDimmer` release has been documented on the [Supported Devices](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#simple-dimmers) page.
