### ISSUE TITLE
Add device request

### ISSUE THREAD

**Issue by camiewwatman** [AMoo-Miki/homebridge-tuya-lan#66]
Name: Kogan SmarterHome RGBW Smart Bulb (running off the TuyaSmart platform). 

Signature: "1":true,"2":"white","3":130,"4":255,"5":"1900000000ff19","6":"00ff0000000000","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000"

Where to buy online: https://www.kogan.com/au/buy/kogan-smarterhome-10w-ambient-rgbw-smart-bulb-e27-2pk/

**Comment by AMoo-Miki** [comment]
This looks like the `RGBTWLight`. Find instructions on the [Supported Devices](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#white-and-color-light-bulbs) page.

Reopen the issue if that doesn't solve your problem.
