### ISSUE TITLE
Add Device Request Globe RGBW Blub

### ISSUE THREAD

**Issue by Rantaholic** [AMoo-Miki/homebridge-tuya-lan#68]
Hi, thanks for all the great work on this project!

Would you be able to add the Globe RGBW Bulb?

[Globe bulbs at Costco](https://www.costco.ca/Globe-Electric-LED-A19-RGB-Smart-Wi-Fi-Bulb.product.100483522.html)

Signature {"20":true,"21":"white","22":500,"23":1000,"24":"007803e803e8","25":"00373702016603e803e800000000373702000e03e803e800000000373702002303e803e800000000373702003003e803e800000000373702003e03e803e800000000","26":0}

I've worked out the dp values

20: Power (true,false)
21: Mode (white,colour,scene)
22: Brightness[only used in white mode] (0-1000)
23: WhiteColourTemp[only used in white mode] (0-1000) 2000k-5000k ie. 2000k=0 3000k=333 5000k=1000
24: Colour[only used in colour mode] 
Combined hex value of Hue(Hex 000-168 [0-360]) Saturation(Hex 000-3e8 [0-1000]) Brightness(Hex 000-3e8 [0-1000]) with 0 separator.
    
Example of 24 
"007803e803e8" 
0 HUE 0 SAT 0 BRT
0 078 0 3e8 0 3e8
078 3e8 3e8 in Hex.
Hue 120(out of 360) Sat 1000(100%) Brt 1000(100%)

Probably not needed:

25: Scene Value[only used in scene mode] 0 separator
Example of 25
"25":"00373702016603e803e800000000373702000e03e803e800000000373702002303e803e800000000373702003003e803e800000000373702003e03e803e800000000"
Scene# 0, Speed 3737, Mode 2, HexColour1 166, Sat 3e8, Brt 3e8, Speed 3737, Mode 2, HexColour2 00e, etc.
Speeds are always a double number from 2828 to 6464 ie. 3232, 4747, 5151,etc

26:Unknown (Was always 0)

Thanks in advance!

**Comment by nicklayb** [comment]
I have a working version of this device on my fork. It works well but I had some glitch while developping, I don't know if they'll come back with more usage. Set your device to `RGBTWGlobeLight` if you want to try it.

**Comment by AMoo-Miki** [comment]
@Rantaholic the data-points for `RGBTWLight` can be overridden in the [latest release](https://github.com/AMoo-Miki/homebridge-tuya-lan#updating) of this plugin. You can find the details on the [Supported Devices](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#white-and-color-light-bulbs) page.

Please reopen the issue if that doesn't help.
