### ISSUE TITLE
tuya door lock

### ISSUE THREAD

**Issue by meme1981** [AMoo-Miki/homebridge-tuya-lan#76]
hello to everybody!!
i have a question;
i wanna buy this look door tuya (or similar)
https://it.aliexpress.com/item/4000065467682.html?spm=a2g0o.productlist.0.0.7c6942b3GKPiqh&algo_pvid=a12a3a20-3e35-40eb-9443-a0edd4015f29&algo_expid=a12a3a20-3e35-40eb-9443-a0edd4015f29-32&btsid=a55e2dad-1f76-4cea-94e9-86eda2c8cbfa&ws_ab_test=searchweb0_0,searchweb201602_3,searchweb201603_53

can you add look door to device list?

**Comment by AMoo-Miki** [comment]
I would love to say yes but until I see the device signature, I won't be able to say. However, if you want the best possible door lock (in my opinion), look at August.

Good luck.

**Comment by meme1981** [comment]
ok, but if you want i can buy it and give to you all access to the item and if you want to a raspberry (ssl) or a computer (team-viewer)

________________________________
Da: Miki <notifications@github.com>
Inviato: mercoledì 4 settembre 2019 09:29
A: AMoo-Miki/homebridge-tuya-lan <homebridge-tuya-lan@noreply.github.com>
Cc: meme1981 <I_R_D_A@msn.com>; Author <author@noreply.github.com>
Oggetto: Re: [AMoo-Miki/homebridge-tuya-lan] tuya door lock (#76)


I would love to say yes but until I see the device signature, I won't be able to say. However, if you want the best possible door lock (in my opinion), look at August.

Good luck.
