### ISSUE TITLE
please add support for "Curtain" - Tuya Smart Life WiFi Curtain Switch

### ISSUE THREAD

**Issue by levieli70** [AMoo-Miki/homebridge-tuya-lan#77]
Tuya Smart Life WiFi Curtain Switch

Ready to handle Curtain with signature {"1":"3"}

https://www.aliexpress.com/item/33018117629.html?spm=a2g0o.productlist.0.0.30835310qhTFn3&algo_pvid=d5b2e180-243a-43ef-b160-fcf2fcd69b57&algo_expid=d5b2e180-243a-43ef-b160-fcf2fcd69b57-43&btsid=c2c75df5-9188-41e3-b082-389ed863c67c&ws_ab_test=searchweb0_0,searchweb201602_1,searchweb201603_52

**Comment by AMoo-Miki** [comment]
Update the plugin and try [these instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#simple-blinds) for `SimpleBlinds`. Lemme know how it goes.

**Comment by levieli70** [comment]
tried it
it's not responding

**Comment by levieli70** [comment]
finaly got it to work:
TNX
{  
   "bridge":{  
      "name":"Homebridge",
      "username": "XX:XX:XX:XX:XX:XX",
      "port":"XXXXX",
      "pin":"XXX-XX-XXX"
   },
    "platforms": [
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Curtain",
                    "type": "SimpleBlinds",
                    "manufacturer": "Tuya",
                    "model": "Tuya",
                    "id": "xxxxxxxxxxxxxx",
                    "key": "xxxxxxxxxxxxx",
  		   "timeToOpen": 45,
		   "timeToTighten": 0,
		   "flipState": false	
                }
            ]
        }
    ]
}

**Comment by AMoo-Miki** [comment]
That is great news. :)

**Comment by ahmdhfz** [comment]
Hi, i've bought this curtain 
https://shopee.com.my/Smart-Life-Smart-Curtain-Motor-Rail-for-home-automation-system-i.33337179.4145972428
I cant connect with homekit even with `SimpleBlinds` .

Value from tuya.com it is={"range":["open","stop","close"]}

hope you can help
