### ISSUE TITLE
Odd message from Tuya switch

### ISSUE THREAD

**Issue by 9SL9** [AMoo-Miki/homebridge-tuya-lan#79]
Here is the log output:

Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
[TuyaAccessory] Odd message from Tuya switch with command 8: A\\�bd9b�^!gʡn޵�h�Q}�
S^�M����nU#���o��E�PE�'���^S�
                             :�bT�WMbQ
                                      y�.(C
[TuyaAccessory] Raw message from Tuya switch (3.3) with command 8: 000055aa00000000000000080000006b00000000332e33000000000000001b00000001415c5c9562643962d15e2167caa16edeb58d68f9517da700535ebf154de1d6fdf76e55071a2382f2ca6ff09ff74591504507f327d9e6ea5e1b5e0053d70c3aa36254e3b1574d6251070b79bd072e2843c1e0affa0000aa55

**Comment by AMoo-Miki** [comment]
The raw message looks valid; the culprit must be a bad `key`.

Also, make sure you don't have `version` in your config for this device.

**Comment by 9SL9** [comment]
Just thought I'd try again, I get this string of errors when I launch the app that controls my plug

![VirtualBox_Ubuntu_10_09_2019_06_18_32](https://user-images.githubusercontent.com/5746558/64563538-faec8000-d392-11e9-8477-a94153ffcfe0.png)

**Comment by AMoo-Miki** [comment]
Can you please get the latest `rc` release using `npm i -g homebridge-tuya-lan@rc`. That should solve many of the problems.

**Comment by 9SL9** [comment]
I see "Intercepted certificate request". On my device I see "Network is unavailable". Then eventually I get this error on my home bridge box (which I'm not sure if this is related to your app or not as I also get other terminal output from the system):
![Screen Shot 2019-09-14 at 9 19 22 am](https://user-images.githubusercontent.com/5746558/64899877-e54bc300-d6d0-11e9-9d35-bb220abf703d.png)

**Comment by buenyamin-olgun** [comment]
Which app are you using and can you use safari to access a https page while using the proxy?

**Comment by 9SL9** [comment]
I’m using this app: Brilliant Smart by Brilliant Lighting (Aust) Pty Ltd

**Comment by AMoo-Miki** [comment]
The `id` and `key` extraction only works with the Tuya Smart app. I have never tried but you could install the Tuya Smart app, add the device to it, extract the `id` and `key`, and get rid of the Tuya Smart app.

**Comment by 9SL9** [comment]
Just tried it by adding the device to the Tuya app with same results. Is there a way to put a different firmware on this thing? Looking at the firmware version on it from within the Tuya app it says I have version 1.0.3. And this is the latest for the brilliant device.

**Comment by AMoo-Miki** [comment]
@9SL9 using the Tuya Smart app, the one with the red icon, did it not give you any `id` and `key`? Did you have the app killed before running `tuya-lan-find`? Did you open the Tuya Smart app afterwards to get an error after roughly a minute about network errors?

**Comment by 9SL9** [comment]
Close the issue, I now have it working, thanks. Yes, indeed I did miss a step - the certificate trust step. Thx

**Comment by AMoo-Miki** [comment]
@9SL9, I am glad your problem is solved. Best of luck.

**Comment by mazafra1** [comment]
I'm having exactly this issue.

Tuya Smart app version: 5.2.0
iPhone 13 on iOS 16.5
Proxy enabled and certificated trusted.

When configuring the proxy on the iPhone I'm getting:
`Error: Error [ERR_TLS_HANDSHAKE_TIMEOUT]: TLS handshake timeout
    at TLSSocket._handleTimeout (_tls_wrap.js:887:22)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ERR_TLS_HANDSHAKE_TIMEOUT'
}`

When opening the Tuya app, I'm getting:
`Error: Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1063:23)
    at TLSSocket.emit (events.js:326:22)
    at net.js:675:12
    at Socket.done (_tls_wrap.js:568:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:675:12) {
  code: 'ECONNRESET'
}`
