### ISSUE TITLE
Configuring RGBTWLight

### ISSUE THREAD

**Issue by nicklayb** [AMoo-Miki/homebridge-tuya-lan#81]
I'm having a [Globe RBG bulb](https://globe-electric.com/en/product/globe-electric-wi-fi-smart-60w-equivalent-multicolor-changing-rgb-tunable-white-dimmable-frosted-led-light-bulb-no-hub-required-a19-e26-base-2-pack34207/) which has the following signature :
```
"dps": {
  "22": 10,
  "23": 1000,
  "24": "003c03e803e8",
  "25": "000e0d00002e03e802cc00000000",
  "26": 0,
  "28": "",
  "20": true,
  "21": "white"
}
```
which dps are the following:
- 22: Brightness in white mode
- 23: Color temperature in white mode
- 24: Seems to be HSL value of the color in color mode seperated by 0. On full saturation and intensity, the last 2 values are a 1000
  - Red (in decimal): `["0", "1000", "1000"]`
  - Blue (in decimal): `["226", "1000", "999"]`
  - Yellow (in decimal): `["60", "1000", "1000"]`
- 20: On/Off state
- 21: Mode (`white` or `colour`)

If you think that such bulb can be configured using current context option, can you please point out how I should configure it? 

If I use the following configuration:
```
{
  "name": "Lampe bureau",
  "id": "xxxxxxxxxxxxxxxxxxx",
  "key": "xxxxxxxxxxxxxxxxxxx",
  "type": "RGBTWLight",
  "dpPower": "20",
  "dpMode": "21",
  "dpBrightness": "23",
  "dpColor": "24"
}
```

I get the following error:
```
homebridge    | [9/9/2019, 9:20:13 PM] [TuyaLan] Ready to handle Lampe bureau (RGBTWLight:3.1) with signature {"20":true,"21":"colour","22":10,"23":1000,"24":"00aa03e803e8","25":"000e0d00002e03e802cc00000000","26":0}
homebridge    | /homebridge/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:159
homebridge    |         const [, h, s, b] = (value || '0000000000ffff').match(/^.{6}([0-9a-f]{4})([0-9a-f]{2})([0-9a-f]{2})$/i);
homebridge    |                                                         ^
homebridge    |
homebridge    | TypeError: (value || "0000000000ffff").match is not a function or its return value is not iterable
homebridge    |     at RGBTWLightAccessory.convertColorFromTuyaToHomeKit (/homebridge/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:159:57)
homebridge    |     at RGBTWLightAccessory._registerCharacteristics (/homebridge/node_modules/homebridge-tuya-lan/lib/RGBTWLightAccessory.js:53:134)
homebridge    |     at TuyaAccessory.BaseAccessory.device.once (/homebridge/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:22:18)
homebridge    |     at Object.onceWrapper (events.js:273:13)
homebridge    |     at TuyaAccessory.emit (events.js:182:13)
homebridge    |     at TuyaAccessory._change (/homebridge/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:372:18)
homebridge    |     at TuyaAccessory._msgHandler_3_1 (/homebridge/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:234:48)
homebridge    |     at queue (/homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:3205:13)
homebridge    |     at Object.process (/homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1431:21)
homebridge    |     at setImmediate$1 (/homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1289:23)
homebridge    |     at Immediate.defer (/homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:73:45)
homebridge    |     at runCallback (timers.js:705:18)
homebridge    |     at tryOnImmediate (timers.js:676:5)
homebridge    |     at processImmediate (timers.js:658:5)
```

Thank you a lot for your awesome work!

**Comment by AMoo-Miki** [comment]
Thanks for digging out what `24` stands for and, as you found out, `RGBTWLight` won't work with this. Lemme add some logic to handle this without needing to add another parameter. I will post an update in a few minutes.

**Comment by AMoo-Miki** [comment]
@nicklayb, please update to the latest unreleased code with `npm i -g AMoo-Miki/homebridge-tuya-lan` and continue to use `RGBTWLight`. This should automatically identify the format; **_if_** it fails, please add `"colorFunction": "HSB"` to override the default.

Please lemme know how it goes.

**Comment by nicklayb** [comment]
So far, switching state works and dimming the white color does work.

These what I can't get to work
- Color changing, I can set to bulb to "color" mode (So it gets blue), but anytime I try to change it, it stays blue and my phone shows red (which is, I think, the fallback color you put in the code). I noticed that the message that is being sent to the bulb does not seem to have the good color format, l.e.:
```
// Setting to a greenish value
homebridge    | [TuyaAccessory] Sending Lampe bureau {"21":"colour","24":"e2ffb8005447ff"}

// Setting to a redish value
homebridge    | [TuyaAccessory] Sending Lampe bureau {"21":"colour","24":"ff00000000ffff"}
```
- Dimming color bulb
- Changing color temperature, in fact, it works but on maximum temperature it only gets to a value lke ~221 and the color does not seem so bright. I tried setting the `maxWhiteColor` to either `221`(the max value I noticed) or `1000` (the max value of the dp) but 221 now gives me ~140 with full brightness and 1000 about 14 so I don't think I really get how this number is mapped with actual bulb value.

**Comment by AMoo-Miki** [comment]
Those color codes are 14 characters long; they are the `HEXHSB` format. The code failed to recognize the correct format automatically. The first time I hear from the device, I count the digits and if it is 12, I mark it as `HSB`, and if it is 14, I mark it as `HEXHSB`. Either the code failed, or the device sent back 14 characters due to an earlier `set` command the code had sent with 14 characters.

If you can, please powercycle the bulb and then restart Homebridge to see if the code does get to figure the format out. If it still sends 14 character long colors in `24`, please add `"colorFunction": "HSB"` to the config block of the device to see if that kicks the colors to work right.

I haven't dealt with the color temperature and brightness yet. When we get the color resolved, I will be asking for your help to figure out:
1. the range of `22`
1. the range of `23` (from your message, it maxes at 1000; is the min 0?)

**Comment by nicklayb** [comment]
Setting the `"colorFunction": "HSB"` works for changing color but dimming the brightness returns back to the red color but correctly dimming the color.

For the white temperature and dimming. Ranges are the following:
- `22`: [10..1000]
- `23`: [0..1000]

I will derp around in the code to see if I can help you out

**Comment by nicklayb** [comment]
I noticed the following, when changing color, I have this kind of log
```
homebridge    | [TuyaAccessory] Sending Lampe bureau {"21":"colour","24":"008d00f003e8"}
homebridge    | [TuyaAccessory] Sending Lampe bureau {"21":"colour","24":"0089020803e8"}
```

But when dimming the color I get the following:
```
homebridge    | [TuyaAccessory] Sending Lampe bureau {"24":"000003e8030c"}
```

Might not be related at all but it looks like when dimming the mode is sent.

**Comment by AMoo-Miki** [comment]
Please update to the latest unreleased code with `npm i -g AMoo-Miki/homebridge-tuya-lan`. Then add the following to your config block:
```json
    "minBrightness": 10,
    "scaleBrightness": 1000,
    "scaleWhiteColor": 1000,
```
This should get the brightness and color temperature to work correctly.

Regarding your second message, during color change, I send the mode, but during brightness change I don't since the plugin has verified the mode earlier in the code. Additionally there was a bug that didn't honor `24` as being the color data-point; I have fixed that too.

If you find everything working, could you please remove `HSB` from the config to see if it continues to work correctly?

**Comment by AMoo-Miki** [comment]
I am glad it is somewhat working. Also, thanks for confirming that the `HSB` is still needed.

The white coming back on is odd. Someone is triggering color temperature change with an odd value. There was a case of `0` being sent which I am handling it; I wonder what this is now. I have thrown in a log message for `setColorTemperature` with the value being called. Can you please update with `npm i -g AMoo-Miki/homebridge-tuya-lan` and see what the message is?

Also, did you by chance have the Tuya app running while this happened?

Can you also remove any `minWhiteColor` and `maxWhiteColor` you might have in your config?

**Comment by nicklayb** [comment]
I can't really tell why, and it annoys me, but this morning everything works, without any changes.

I did not even had to update to your latest changes. I did try to open the Tuya App (Globe for this bulb) and it don't switch back to tunable white.

Everything works perfectly fine now. I'm sorry that you had to do some unused work I think we can close this and thank you again for taking the time to debug this with me. Here's my whole config if anyone has similar issues
```
{
  "name": "Lampe bureau",
  "id": "XXXXXXX",
  "key": "XXXXXXX",
  "type": "RGBTWLight",
  "dpPower": "20",
  "dpMode": "21",
  "dpBrightness": "22",
  "dpColorTemperature": "23",
  "dpColor": "24",
  "maxWhiteColor": "221",
  "colorFunction": "HSB",
  "minBrightness": 10,
  "scaleBrightness": 1000,
  "scaleWhiteColor": 1000
},
```

**Comment by AMoo-Miki** [comment]
You don't need to apologize. I am glad that everything works fine now, and thanks for helping add yet another type of device to our arsenal.

**Comment by iRayanKhan** [comment]
Had this exact issue just now, your config just fixed it for me. Thank you!!

**Comment by kanmapoo** [comment]
hello, I installed this exact config and it worked perfectly for me although I don't really know why ;) Thanks for the good work
