### ISSUE TITLE
Unable to run tuya-lan-find to find key's and id's.

### ISSUE THREAD

**Issue by charlesomer** [AMoo-Miki/homebridge-tuya-lan#82]
First, I had to manually install the npm `debug` package.
Now I am seeing the following error.
I'm running homebridge on a Raspberry Pi Zero W.
```
/usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175
    let {address, port} = proxy.httpServer.address();
                                           ^

TypeError: Cannot read property 'address' of undefined
    at proxy.listen (/usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175:44)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:62:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:130:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:988:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3885:13
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/mkdirp/index.js:47:53
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by AMoo-Miki** [comment]
@charlesomer, could you please post what the problem was so that I can help other who face the same issue?

**Comment by charlesomer** [comment]
It was an issue with my Raspberry Pi accounts rather than an issue with this project! Not entirely sure what, but I under up running the discovery process (to find keys and ids) on a Mac instead.

**Comment by AMoo-Miki** [comment]
Cool. Best of luck and don't hesitate to post back if you face any more trouble.

**Comment by wenoptics** [comment]
I had a same issue with `Cannot read property 'address' of undefined` when I run `tuya-lan-find` first. Looks like it's caused when I have multi net interfaces on (even with `--ip <ip>` ). 

I guess I fix it by temporarily down the unused net interfaces.

**Comment by Hendriks046** [comment]
I am using hoobs. and trying to discover the ID & KEY. when I type in: tuya-lan-find command. I get the same error as shown as topic. I am not able to fix it. I saw messages of changing the port to 8081 or 8001. but nothing seems to work. can someone help me out please?

**Comment by charlesomer** [comment]
@Hendriks046 Unfortunately, I didn't work out what was causing the issue since I just tried it on another machine which worked.

**Comment by dasNavy** [comment]
You probably haven't run with admin rights: sudo tuya-lan-find --ip 0.0.0.0

**Comment by tim-jc** [comment]
I had the same issue, but running `sudo tuya-lan-find` sorted it. This on a raspberry pi.

**Comment by 1aranzant** [comment]
I get the following error: 
`Error: Error: listen EADDRINUSE: address already in use :::8080
`
8080 is my Phoscon web interface

**Comment by joshua-obvience** [comment]
Seems like everyone is getting different errors but errors nonetheless.

```
#Intercepted certificate request
Error: ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN [Error: 3972:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1546:SSL alert number 46
] {
  library: 'SSL routines',
  function: 'ssl3_read_bytes',
  reason: 'sslv3 alert certificate unknown',
  code: 'ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN'
}
Error: ETIMEDOUT Error: connect ETIMEDOUT 17.57.152.22:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '17.57.152.22',
  port: 443
}
```
