### ISSUE TITLE
Led Strip Controller

### ISSUE THREAD

**Issue by twistedindustries** [AMoo-Miki/homebridge-tuya-lan#83]
I was hoping to add a new device but I am stuck with the error when trying to run it as a SimpleLight: Malformed update from Planter Box with command 10: json obj data unvalid

It's an led strip controller like this one: https://www.amazon.com/gp/product/B07L8YYW26/ref=ppx_yo_dt_b_asin_title_o06_s01?ie=UTF8&psc=1

I was able to get the schema and extras

schema:
`[
  {
    "mode": "rw",
    "code": "led_switch",
    "name": "\\u5f00\\u5173",
    "property": {
      "type": "bool"
    },
    "iconname": "icon-dp_power",
    "id": 1,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "work_mode",
    "name": "\\u6a21\\u5f0f",
    "property": {
      "range": [
        "white",
        "colour",
        "scene",
        "scene_1",
        "scene_2",
        "scene_3",
        "scene_4",
        "music"
      ],
      "type": "enum"
    },
    "iconname": "icon-dp_box2",
    "id": 2,
    "type": "obj",
    "desc": "\\u589e\\u52a0\\u97f3\\u4e50\\u6a21\\u5f0f"
  },
  {
    "mode": "rw",
    "code": "bright_value",
    "name": "\\u4eae\\u5ea6",
    "property": {
      "unit": "",
      "min": 25,
      "max": 255,
      "scale": 0,
      "step": 1,
      "type": "value"
    },
    "id": 3,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "temp_value",
    "name": "\\u51b7\\u6696",
    "property": {
      "unit": "",
      "min": 0,
      "max": 255,
      "scale": 0,
      "step": 1,
      "type": "value"
    },
    "id": 4,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "colour_data",
    "name": "\\u5f69\\u5149\\u6a21\\u5f0f\\u6570",
    "property": {
      "type": "string",
      "maxlen": 14
    },
    "id": 5,
    "type": "obj",
    "desc": "rgbhsv"
  },
  {
    "mode": "rw",
    "code": "scene_data",
    "name": "\\u60c5\\u666f\\u6a21\\u5f0f\\u6570",
    "property": {
      "type": "string",
      "maxlen": 14
    },
    "id": 6,
    "type": "obj",
    "desc": "rgbhsv"
  },
  {
    "mode": "rw",
    "code": "flash_scene_1",
    "name": "\\u67d4\\u5149\\u6a21\\u5f0f",
    "property": {
      "type": "string",
      "maxlen": 14
    },
    "id": 7,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "flash_scene_2",
    "name": "\\u7f24\\u7eb7\\u6a21\\u5f0f",
    "property": {
      "type": "string",
      "maxlen": 44
    },
    "id": 8,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "flash_scene_3",
    "name": "\\u70ab\\u5f69\\u6a21\\u5f0f",
    "property": {
      "type": "string",
      "maxlen": 14
    },
    "id": 9,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "flash_scene_4",
    "name": "\\u6591\\u6593\\u6a21\\u5f0f",
    "property": {
      "type": "string",
      "maxlen": 44
    },
    "id": 10,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "wr",
    "code": "music",
    "name": "\\u97f3\\u4e50\\u706f",
    "property": {
      "type": "string",
      "maxlen": 255
    },
    "id": 101,
    "type": "obj",
    "desc": "\\u97f3\\u4e50\\u706f"
  }
]`

extra:
`[
  {
    "id": 1,
    "inputStyle": "",
    "inputType": "plain"
  },
  {
    "id": 2,
    "inputStyle": "",
    "inputType": "plain"
  },
  {
    "id": 3,
    "inputStyle": "",
    "inputType": " "
  },
  {
    "id": 4,
    "inputStyle": "",
    "inputType": " "
  }
]`

**Comment by AMoo-Miki** [comment]
This is great; we didn't have any LED strips and it's good to confirm one.

`json obj data unvalid` is a Tuya firmware issue and several devices suffer from it. Even Tuya's own app receives this error. I have reached out to them and one of the vendors to find a solution.

Also, thanks for adding the schema to the issue. This looks identical to `RGBTWLight` and you can find the instructions and a sample config on the [Supported Devices](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#white-and-color-light-bulbs) page. The good news is that your LED strip is pretty standard and you don't need any of the overrides; just setting the `type` to `RGBTWLight` would get it to work just right.

Please let me know how it goes.

**Comment by twistedindustries** [comment]
I did try that one and I never get the "Ready to handle" message and the device doesn't respond in homekit.  It seems to see the device and does connect to it.  I don't see any other related errors in debug mode.  Any ideas?

**Comment by AMoo-Miki** [comment]
Oops. I should have mentioned that handling `json obj data unvalid` is still in `rc`. Please update using `npm i -g homebridge-tuya-lan@rc`.

**Comment by twistedindustries** [comment]
I updated to the rc and it didn't change anything.  Tried as both RGBTWLight and SimpleLight, still never receive a ready to handle message for the device.

**Comment by AMoo-Miki** [comment]
Can you post anything you have in the logs related to the plugin so that I can piece together where things are not going as planned?

**Comment by twistedindustries** [comment]
I setup another instance of homebridge with the led strip by itself.  Here is the entire log:
`[9/16/2019, 7:32:37 PM] [TuyaLan] Initializing TuyaLan platform...
[9/16/2019, 7:32:37 PM] [TuyaLan] Marked Planter Box unreachable by faulting Service.Planter Box.On
[9/16/2019, 7:32:38 PM] [TuyaLan] Starting discovery...
  EventedHTTPServer Server listening on port 49385 +0ms
[9/16/2019, 7:32:38 PM] Homebridge is running on port 49385.
[TuyaDiscovery] Discovery started on port 6666.
[TuyaDiscovery] Discovery started on port 6667.
  EventedHTTPServer [::ffff:10.0.1.26] New connection from client +968ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP server listening on port 53012 +0ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP request: /pair-verify +9ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +0ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 1/2 +3ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP Response is finished +50ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP request: /pair-verify +28ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +0ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 2/2 +1ms
  HAPServer [AC:2A:9F:18:2A:4C] Client 5B113236-21EA-43FE-95BE-D211FB209A12 verification complete +33ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP request: /accessories +8ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP Response is finished +2ms
[9/16/2019, 7:32:39 PM] [TuyaLan] Discovered a device that has not been configured yet (50642000840d8e5279ec@10.0.1.40).
  EventedHTTPServer [::ffff:10.0.1.26] HTTP request: /characteristics +550ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:10.0.1.26] HTTP Response is finished +2ms
[9/16/2019, 7:32:40 PM] [TuyaLan] Discovered Planter Box (eb69c9c7e63c330f07rjv0) identified as RGBTWLight (3.2)
[9/16/2019, 7:32:40 PM] [TuyaLan] Discovered a device that has not been configured yet (04408358bcddc294adab@10.0.1.14).
[9/16/2019, 7:32:40 PM] [TuyaLan] Connected to Planter Box
[TuyaAccessory] Sending first query to Planter Box (3.2)
[TuyaAccessory] Malformed update from Planter Box with command 10: json obj data unvalid
[TuyaAccessory] Raw update from Planter Box (3.2) with command 10: 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55
[9/16/2019, 7:32:45 PM] [TuyaLan] Discovered a device that has not been configured yet (15831230cc50e3036ff9@10.0.1.15).
  EventedHTTPServer [::ffff:10.0.1.5] New connection from client +1m
  EventedHTTPServer [::ffff:10.0.1.5] HTTP server listening on port 53033 +0ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP request: /pair-verify +4ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +0ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP Response is finished +15ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP request: /pair-verify +45ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +1ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 2/2 +1ms
  HAPServer [AC:2A:9F:18:2A:4C] Client C163334B-9487-44F2-AA95-7F1021A1936E verification complete +21ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP request: /accessories +78ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.1.5] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.3] New connection from client +3s
  EventedHTTPServer [::ffff:10.0.1.3] HTTP server listening on port 53035 +0ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP request: /pair-verify +4ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +0ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP Response is finished +17ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP request: /pair-verify +23ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: POST /pair-verify +1ms
  HAPServer [AC:2A:9F:18:2A:4C] Pair verify step 2/2 +0ms
  HAPServer [AC:2A:9F:18:2A:4C] Client 5B113236-21EA-43FE-95BE-D211FB209A12 verification complete +25ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP request: /accessories +16ms
  HAPServer [AC:2A:9F:18:2A:4C] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.3] HTTP Response is finished +1ms`

**Comment by twistedindustries** [comment]
The issue seems to be under the `_msgHandler_3_1` method.  It looks like it should hangup in the first if here, but instead it's throwing the two errors in `catch` before dieing.
`if (data == 'json obj data unvalid') {
                        console.log(`[TuyaAccessory] ${this.context.name} (${this.context.version}) didn't respond with its current state.`);
                        console.log('change3');
                        this.emit('change', {}, this.state);
                        break;
                    }

                    try {
                        data = JSON.parse(data);
                    } catch (ex) {
                        console.log(`[TuyaAccessory] Malformed update from ${this.context.name} with command ${cmd}:`, data);
                        console.log(`[TuyaAccessory] Raw update from ${this.context.name} (${this.context.version}) with command ${cmd}:`, task.msg.toString('hex'));
                        break;
                    }`

**Comment by twistedindustries** [comment]
I did another test where I forced that device to `this.emit('change', {}, this.state);` and it returned a `Ready to handle Planter Box (SimpleLight:3.2) with signature {}` but still doesn't respond to any command.

**Comment by AMoo-Miki** [comment]
This is great. The device reporting `json obj data unvalid` is a bug in Tuya and the empty `change` is meant to force the device to simply show up. I have reached out to Tuya and we have started a conversation on this.

I don't have a 3.2 device and don't have packet captures for it; I will need your help figuring this one out.
1. Install the latest unreleased code with `npm i -g AMoo-Miki/homebridge-tuya-lan`.
1. Restart Homebridge.
1. While you have the logs open and **_after_** you see `Malformed update from Planter Box`, launch the Tuya Smart app. If the Tuya app is opened before the plugin, it will prevent the pluginfrom talking to the device.
1. Turn the light on or off in the app.
1. The log should show you `Odd message from Planter Box` followed by `Raw message from Planter Box`. The raw message is the one we are interested in, starting with `000055aa` and ending in `0000aa55`.
1. Run `tuya-lan decode --use 3.2`.
1. Enter the `key` for the device when prompted to.
1. Paste the raw message from earlier.

See if it was able to decode it successfully. If it does, I know what to change to get your device to work. If not, we will figure something out.

**Comment by twistedindustries** [comment]
Thanks for the help!  I'd be super happy if we can get this working.

Here is what I got, the command 8 message is what came on when I turned the device on from the tuya app.
`[TuyaAccessory] Sending first query to Planter Box (3.2)
[TuyaAccessory] Malformed update from Planter Box with command 10: json obj data unvalid
[TuyaAccessory] Raw update from Planter Box (3.2) with command 10: 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55
[TuyaAccessory] Odd message from Planter Box with command 8: $���]�4��T���_v�i�rߤ���p���Sa�
[TuyaAccessory] Raw message from Planter Box (3.2) with command 8: 000055aa00000000000000080000004b00000000332e32000000000000018300000001b4443dee07f16bd6a13720d53be5240fedddf25dff3497ae54e6d9da5f76b269bb72dfa4a8c4f0707ff58ae2530e61a03f9f37780000aa55`

When trying to decode I get the message `The key contains the wrong number of characters; try again.`

**Comment by AMoo-Miki** [comment]
The key must be 16 characters long; how many are yours?

**Comment by twistedindustries** [comment]
Sorry I was misunderstanding what it meant by key.  Here is what I got below.  The first was the command 8 which showed up after turning off the light from the tuya app.  The second message is command 10 from initial startup.
`Enter the encrypted message: 000055aa00000000000000080000004b00000000332e3200000000000001b300000001663b109f501772507f94a124bf77562c6096a7eaafd2e2378909a27b6febe2765cf19a67bd8ed21aec179c871c7c98db210adbf00000aa55
Cmd > 8  	Len > 91	Size > 75	Seq > 0
CRC > 	Pass
*Failed > 000055aa00000000000000080000004b00000000332e3200000000000001b300000001663b109f501772507f94a124bf77562c6096a7eaafd2e2378909a27b6febe2765cf19a67bd8ed21aec179c871c7c98db210adbf00000aa55

Enter the encrypted message: 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55
Cmd > 10  	Len > 49	Size > 33	Seq > 0
CRC > 	Pass
*Failed > 000055aa000000000000000a00000021000000016a736f6e206f626a206461746120756e76616c6964d25378690000aa55`

**Comment by AMoo-Miki** [comment]
Are you sure you are using the correct `key`? I ask because it failed to decode any of those messages.

**Comment by twistedindustries** [comment]
@AMoo-Miki  just emailed it over

**Comment by AMoo-Miki** [comment]
Thanks; got it. I managed to figure it out. Lemme make some changes and have you test it.

**Comment by twistedindustries** [comment]
I was able to get it working with one edit.
TuyaAccessory:297
`if ((cmd === 10 && decryptedMsg === 'json obj data unvalid') || (cmd === 10 && decryptedMsg === 'data format error')) {`

My decryptedMsg said "data format error".

It also doesn't get the current state properly but does work once I interact with it.
`Ready to handle Planter Box (RGBTWLight:3.2) with signature {}`

**Comment by AMoo-Miki** [comment]
We shouldn't get `data format error`. Lemme see if there is a difference between what is being sent by Tuya and the plugin.

**Comment by AMoo-Miki** [comment]
If you are okay editing the code, can you please edit the `TuyaAccessory.js` file  at around line 370, after `Sending first query`, and swap `devId` and `gwId`? It _might_ be complaining about that.

**Comment by hawka97** [comment]
I am new to homebridge and just attempted to connect my LED Light Strip. I got similar errors to what was seen above, and I've made the same code edits, including the one from the last comment. I am also running the latest from `npm i -g AMoo-Miki/homebridge-tuya-lan`. I am still having trouble getting it to work.

In my logs, I am getting lots of UDP messages:
`[10/18/2019, 8:35:19 PM] [TuyaLan] Starting discovery...
[10/18/2019, 8:35:19 PM] Homebridge is running on port 51826.
[TuyaDiscovery] Discovery started on port 6666.
[TuyaDiscovery] Discovery started on port 6667.
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[10/18/2019, 8:35:24 PM] [TuyaLan] Discovered Kitchen Light Strip (eb2ba4f1eae0ddaed1u92c) identified as RGBTWLight (3.2)
[TuyaAccessory] Changing ping gap for Kitchen Light Strip to 9s
[10/18/2019, 8:35:24 PM] [TuyaLan] Connected to Kitchen Light Strip
[TuyaAccessory] Sending first query to Kitchen Light Strip (3.2)
[TuyaAccessory] Odd message from Kitchen Light Strip with command 10: data format error
[TuyaAccessory] Raw message from Kitchen Light Strip (3.2) with command 10: 000055aa000000010000000a0000001d000000016461746120666f726d6174206572726f7271bf61a40000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55`

and when I try to control the LED Strip from HomeKit, see this: 
`[TuyaAccessory] Sending Kitchen Light Strip {"1":true}
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaAccessory] Sending Kitchen Light Strip {"1":false}
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55`
(Tap to turn on, wait 10-15 secs, tap to turn off)

When I open the previously closed Tuya based app to control from there, I see this:
`[TuyaAccessory] Heard back from Kitchen Light Strip with command 8
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55
[TuyaAccessory] Heard back from Kitchen Light Strip with command 8
[TuyaDiscovery] UDP from 172.19.1.183:6666 0x000055aa...0x0000aa55`
(Tap to turn on, wait 10-15 secs, tap to turn off)

My result of tuya-lan-find --schema is here:
`Intercepted certificate request
Intercepted config from Tuya

Found 1 device:
[
  {
    name: 'RGBW LED Strip',
    id: 'eb2ba4f1eae0ddaed1u92c',
    key: '766bXXXXXXXXXXXX',
    def: {
      schema: '[{"mode":"rw","code":"switch_led","name":"\\u5f00\\u5173","property":{"type":"bool"},"id":20,"type":"obj","desc":""},{"mode":"rw","code":"work_mode","name":"\\u6a21\\u5f0f","property":{"range":["white","colour","scene","music"],"type":"enum"},"id":21,"type":"obj","desc":""},{"mode":"rw","code":"bright_value","name":"\\u4eae\\u5ea6\\u503c","property":{"unit":"","min":10,"max":1000,"scale":0,"step":1,"type":"value"},"id":22,"type":"obj","desc":""},{"mode":"rw","code":"colour_data","name":"\\u5f69\\u5149","property":{"type":"string","maxlen":255},"id":24,"type":"obj","desc":""},{"mode":"rw","code":"scene_data","name":"\\u573a\\u666f","property":{"type":"string","maxlen":255},"id":25,"type":"obj","desc":""},{"mode":"rw","code":"countdown","name":"\\u5012\\u8ba1\\u65f6\\u5269\\u4f59\\u65f6\\u95f4","property":{"unit":"","min":0,"max":86400,"scale":0,"step":1,"type":"value"},"id":26,"type":"obj","desc":""},{"mode":"wr","code":"control_data","name":"\\u8c03\\u8282","property":{"type":"string","maxlen":255},"id":28,"type":"obj","desc":""}]',
      extras: '[{"id":22,"inputStyle":"","inputType":"percent1"},{"id":26,"inputStyle":"","inputType":""}]',
    },
  },
]`

**Comment by arisarts** [comment]
Hi !

I also have one led strip controller and with with your plug in I was able add it in my homebridge setup on my pi.
I manage to setup it as RGBTW and its working on my iPhone as with tuya app .
What I want to do though is to convert the color output and match it to my led strip.
The led strip is only White cold and warm 5050 leds and I have connect it using green and blue output of the controller .Is this possible to do it through the configuration parameters or I need something more to do it ? 
Do you know any method to achieve that ? 

Great work and great guide / wiki btw.

Thank you 

Aris (Greece)

**Comment by twistedindustries** [comment]
@arisarts  Have you tried `TWLight` instead of `RGBTWLight`?

**Comment by arisarts** [comment]
> @arisarts Have you tried `TWLight` instead of `RGBTWLight`?
Yes I did and it’s working but with limited functions on off only ...

**Comment by twistedindustries** [comment]
@AMoo-Miki I've finally had a chance to circle back to this and was hoping to get this resolved.  I still have to have the following code on TuyaAccessory.js:297
`if ((cmd === 10 && decryptedMsg === 'json obj data unvalid') || (cmd === 10 && decryptedMsg === 'data format error')) {`

I tried the following fix and that didn't seem to work
> If you are okay editing the code, can you please edit the `TuyaAccessory.js` file at around line 370, after `Sending first query`, and swap `devId` and `gwId`? It _might_ be complaining about that.

**Comment by AMoo-Miki** [comment]
@twistedindustries, yeah it seems to still be needed. Seems to be a flaw with the API on the device firmware. I will add this to the release version to benefit others too. I have a few devices that do this and the Tuya app itself can't figure out their initial state without interacting with them first. Please raise an issue if there is anything else I can help you with.

@hawka97, thanks for the schema. The `id` parameters for your LED strip need to be configured correctly. Follow the [configuration parameters for RGBTWLight](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#white-and-color-light-bulbs) and set dpPower to 20, dpMode to 21, dpBrightness to 22, dpColor to 24. You will have an extra functionality of changing the white color temperature which your strip doesn't really have but that's the only way I can have RGB and whites mixed. If you still have problems, please create a new issue and reference our conversation here.

@arisarts, to be able to help you better, follow [these steps to get the schema](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#adding-support-for-new-devices). Please create a new issue so you get an undivided attention; this will also help me not confuse you with someone else :)
