### ISSUE TITLE
SimpleBlinds variation

### ISSUE THREAD

**Issue by NamelessPharaoh** [AMoo-Miki/homebridge-tuya-lan#89]
OK, if any one else faces this issue; with some blinds the constants sent by the controls are not '1', '2'
they need to be replaced by 
'1' = 'off'
'2' = 'on'

what I did as there is no correction at the moment : 
sudo nano /usr/local/lib/node_modules/homebridge-tuya-lan/lib/SimpleBlindsAccessory.js

then modify the file at line 22-25 with the following:

        this.cmdOpen = 'on';
        this.cmdClose = 'off';
        if (!!this.device.context.flipState) {
            this.cmdOpen = 'off';
            this.cmdClose = 'on';

**Comment by AMoo-Miki** [comment]
Thanks for posting the workaround.

I have these configurable in the `rc` releases. I would push that branch and update the documentation as soon as the changes have been tested.

**Comment by NamelessPharaoh** [comment]
beware as I redownloaded the RC due to some issues, this problem is still present

**Comment by hsismeiro** [comment]
hi! i'm new with homebridge, how can i modify the file at the line 22-25?
