### ISSUE TITLE
"noChildLock": true for Air Conditioner

### ISSUE THREAD

**Issue by KrtNthny** [AMoo-Miki/homebridge-tuya-lan#9]
Hi,

will the "noChildLock": true work for my Air Conditioner because it doesn't have the child lock setting.  I added it to the config.json file 

```
{
        "platform": "TuyaLan",
        "devices": [
          {
            "name": "Air Conditioner",
            "type": "AirConditioner",
            "manufacturer": "Kogan",
            "model": "KAPRA14WFGA",
            "id": "123456789abcdefghijklmn",
            "key": "123456789abcdefg",
            "fanSpeedSteps": 3,
            "minTemperature": 17,
            "maxTemperature": 30,
            "noChildLock": true
          }
        ]
      }
```

I restarted homebridge but there was no change. Do I have to go into the accessories folder in /Users/username/.homebridge/ and delete the "cachedAccessories" file?

**Comment by AMoo-Miki** [comment]
The child lock is function that the AC has to have built in. If your AC does not have that functionality, set the `noChildLock` to true.  If you don't set it, Home app will show a toggle in the `Settings` of your device which will do nothing for you. The only thing this parameter does is hide or show the toggle within the Home app.

Yes; any change to the config would need a cleanup of the cached accessories. Lemme know how things go.

Good luck :)

**Comment by KrtNthny** [comment]
I set the noChildLock to true in the config file and deleted the cached file but the feature is still there. That setting doesn’t do anything for me I was just trying to remove it but that didn’t work.

Sent from Kurt’s iPhone

**Comment by AMoo-Miki** [comment]
Lemme check it out on my end. I will let you know in a couple of hours.

**Comment by AMoo-Miki** [comment]
Kurt, sorry that this took so much time but fortunately it is solved. You can get the latest, yet unreleased, code with `npm i -g AMoo-Miki/homebridge-tuya-lan`. Please reopen if the problem is not solved.

**Comment by KrtNthny** [comment]
Thankyou. No problem. I will try it tomorrow.
