### ISSUE TITLE
Homebridge crash after restart 

### ISSUE THREAD

**Issue by omriileviii** [AMoo-Miki/homebridge-tuya-lan#90]
Hello
After restart Homebridge tuya-lan crash.
Only after delete folder persists and accessories that fix.

**Comment by xdmate** [comment]
I hope the dev is ok. We were talking days ago, and he was very active, now hes kinda disappeared. 

In the mean time try the rc version: npm i -g AMoo-Miki/homebridge-tuya-lan

**Comment by AMoo-Miki** [comment]
Thanks @xdmate. The correct command to get the `rc` release is `npm i -g homebridge-tuya-lan@rc`.

For the very brave who are willing to risk the bleeding edge changes `npm i -g AMoo-Miki/homebridge-tuya-lan` would update to the latest code.

@omriileviii Let us know if that doesn't solve your problem.

**Comment by xdmate** [comment]
@AMoo-Miki You got it dude! Glad all is well. :)

**Comment by AMoo-Miki** [comment]
@omriileviii, please reopen the issue if you still have problems.

@xdmate Thanks :)
