### ISSUE TITLE
3.3 version to be supported

### ISSUE THREAD

**Issue by mourraille** [AMoo-Miki/homebridge-tuya-lan#91]
I was able to successfully install the plugin. No errors on logs. Everything seems to be working, even in the home app, except for the fact my rgb lamps aren't responding. Could it be a 3.2 <-> 3.3 protocol issue. As my devices are using this version. 

Logs looking good : 

`0|homebridge -I  | [TuyaAccessory] setColorTemperature: 152
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"2":"white","4":148}
0|homebridge -I  | [TuyaAccessory] setColorTemperature: 140
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"2":"white","4":157}
0|homebridge -I  | [TuyaAccessory] setColorTemperature: 156
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"2":"white","4":145}
0|homebridge -I  | [TuyaAccessory] setColorTemperature: 0
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"1":false}
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"1":true}
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"1":false}
0|homebridge -I  | [TuyaAccessory] Sending Bedroom Light {"1":true}`

**Comment by AMoo-Miki** [comment]
Looking at the logs, when it says `Discovered ...` does it tell you what version the device is? 3.1, 3.2, or 3.3?

Follow these steps in this order:
1. Make sure the Tuya Smart app is closed fully.
1. Restart Homebridge.
1. Open the logs and wait for the message that device was discovered.
  * Take a note of the signature if one is shown.
1. Open the Tuya Smart app.
1. Change the color on the lamp in Tuya Smart or turn it off.

What do you see in the logs as soon as you do that?

**Comment by mourraille** [comment]
[2019-9-30 20:00:32] [TuyaLan] Discovered Bedroom Light (85524870bcddc223b315) identified as RGBTWLight (3.3)

**Version is 3.3**
`[2019-9-30 20:00:36] [TuyaLan] Ready to handle Living Room Light (RGBTWLight:3.3) with signature `

**Signature retrieved:**
`{"20":true,"21":"white","22":1000,"24":"000003e803e8","25":"000e0d00002e03e802cc00000000","26":0}`

**Changing the color on the lamp in Tuya Smart or turn it off shows this:** 
[TuyaAccessory] Heard back from Bedroom Light with command 8

**Comment by AMoo-Miki** [comment]
Looks like the problem is with the `id` parameters of this device are not per the common ones. Follow [these configuration steps](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#white-and-color-light-bulbs) to set dpPower to 20, dpMode to 21, dpBrightness to 22, and dpColor to 24.

This device doesn't seem to have tunable whites but you can continue to use it as RGBTWLight while I figure a way out to fake the white tunability.

Please reopen this issue if that doesn't solve your problem.

**Comment by jakubhavel** [comment]
hi @AMoo-Miki 
I managed brightness to get working (thanks to configuration of dpPower, dpMode, dpBrightness and dpColor mentioned above) – how is it looking with white tunability please? Thnaks
