### ISSUE TITLE
Separating Multi Outlet Devices in Homekit so that each outlet shows up separately

### ISSUE THREAD

**Issue by TheHomekitWayFinder** [AMoo-Miki/homebridge-tuya-lan#92]
Would it be possible to create a new device type that allows the same device to be listed multiple time while showing each outlet separately in HomeKit by specifying the outlet id in the config file that then tells HomeKit which outlet of the powerboard to display and therefore it doesn't show the master board in HomeKit and as each outlet would display separately, therefore, it would allow each outlet to show up in different rooms as I have an Arlec Grid Connect Power Strip and i want to be able to have 2 outlets show up in a different room to the other 2 outlets as I have the board in a garage but the outlets lead outside for use on lights and other outdoor appliances.

**Comment by codyc1515** [comment]
iOS 13 grouped all of the services (each outlet) by accessory (your power strip). iOS 13.2 brings back the option to get separate tiles per service (outlet) so I would say to wait for this to come out then check it.

**Comment by TheHomekitWayFinder** [comment]
@codyc1515 Thanks for that information, I know that on macOS it shows each device seperatly but it doesnt allow you to assign each of those individual outlets to different rooms, and from what you have said im not sure whether it allows you to set them to different rooms or whether everything on the same powerboard has to be in the same room.

**Comment by codyc1515** [comment]
Why would something on the same power board be in another room?

**Comment by TheHomekitWayFinder** [comment]
So I have the powerboard in my garage but 2 of the outlets lead to my patio through the use of extension leads and i have my patio and garage set up as different rooms in HomeKit. If this is not the case then would it be possible to create a new device type that takes each outlet of the powerboard and basically tells HomeKit that they are different devices or not.

**Comment by codyc1515** [comment]
What you are suggesting I am sure is possible, but is not the intent of HomeKit. More-so, this doesn't really sound electrically safe.

**Comment by TheHomekitWayFinder** [comment]
> What you are suggesting I am sure is possible, but is not the intent of HomeKit. More-so, this doesn't really sound electrically safe.

in what way don't you think it sounds electrically safe

**Comment by codyc1515** [comment]
You're running extension leads from a multi-board.

**Comment by TheHomekitWayFinder** [comment]
> You're running extension leads from a multi-board.

So I have one extension lead running from the board to an outdoor appliance, the extension lead is heavy duty and is rated for outdoor use along with all connections being weatherproofed using appropriate lead boxes and then the rest of them are outdoor lights running into the garage in order to have smart control over them.

**Comment by codyc1515** [comment]
Have you installed iOS 13.2 and tried the separate tile?

**Comment by TheHomekitWayFinder** [comment]
Yeah I have installed 13.2 the other day and seperate tiles work but it doesn’t allow me to set different rooms for each device

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
