### ISSUE TITLE
Door/window and motion sensors?

### ISSUE THREAD

**Issue by Bogdis** [AMoo-Miki/homebridge-tuya-lan#93]
Hello.
Is there any door/window and motion sensors that works with this plugin?
Thanks

**Comment by jeylites** [comment]
@Bogdis did you manage to get the motion and contact sensors to work?

**Comment by Bogdis** [comment]
> @Bogdis did you manage to get the motion and contact sensors to work?

Hi, no i didn't find any sensors that work so i got the aqara hub and sensors instead.

**Comment by jeylites** [comment]
good to know. I'm currently trying to decide between a Wifi and ZigBee tuya solution. But I think the plugin itself doesn't support it yet since I don't see any material about sensors in the wiki.
